// Code generated by ent, DO NOT EDIT.

package instrument

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the instrument type in the database.
	Label = "instrument"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAssetClass holds the string denoting the asset_class field in the database.
	FieldAssetClass = "asset_class"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldDivider holds the string denoting the divider field in the database.
	FieldDivider = "divider"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldIsPause holds the string denoting the is_pause field in the database.
	FieldIsPause = "is_pause"
	// EdgeStates holds the string denoting the states edge name in mutations.
	EdgeStates = "states"
	// EdgeSyncTasks holds the string denoting the sync_tasks edge name in mutations.
	EdgeSyncTasks = "sync_tasks"
	// Table holds the table name of the instrument in the database.
	Table = "instruments"
	// StatesTable is the table that holds the states relation/edge.
	StatesTable = "states"
	// StatesInverseTable is the table name for the State entity.
	// It exists in this package in order to avoid circular dependency with the "state" package.
	StatesInverseTable = "states"
	// StatesColumn is the table column denoting the states relation/edge.
	StatesColumn = "instrument_id"
	// SyncTasksTable is the table that holds the sync_tasks relation/edge.
	SyncTasksTable = "sync_tasks"
	// SyncTasksInverseTable is the table name for the SyncTask entity.
	// It exists in this package in order to avoid circular dependency with the "synctask" package.
	SyncTasksInverseTable = "sync_tasks"
	// SyncTasksColumn is the table column denoting the sync_tasks relation/edge.
	SyncTasksColumn = "instrument_id"
)

// Columns holds all SQL columns for instrument fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAssetClass,
	FieldIsActive,
	FieldDivider,
	FieldStartDate,
	FieldIsPause,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultIsPause holds the default value on creation for the "is_pause" field.
	DefaultIsPause bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Instrument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAssetClass orders the results by the asset_class field.
func ByAssetClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetClass, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByDivider orders the results by the divider field.
func ByDivider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDivider, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByIsPause orders the results by the is_pause field.
func ByIsPause(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPause, opts...).ToFunc()
}

// ByStatesCount orders the results by states count.
func ByStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatesStep(), opts...)
	}
}

// ByStates orders the results by states terms.
func ByStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySyncTasksCount orders the results by sync_tasks count.
func BySyncTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSyncTasksStep(), opts...)
	}
}

// BySyncTasks orders the results by sync_tasks terms.
func BySyncTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSyncTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StatesTable, StatesColumn),
	)
}
func newSyncTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SyncTasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SyncTasksTable, SyncTasksColumn),
	)
}
