// Code generated by ent, DO NOT EDIT.

package instrument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldDescription, v))
}

// AssetClass applies equality check predicate on the "asset_class" field. It's identical to AssetClassEQ.
func AssetClass(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldAssetClass, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldIsActive, v))
}

// Divider applies equality check predicate on the "divider" field. It's identical to DividerEQ.
func Divider(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldDivider, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldStartDate, v))
}

// IsPause applies equality check predicate on the "is_pause" field. It's identical to IsPauseEQ.
func IsPause(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldIsPause, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContainsFold(FieldDescription, v))
}

// AssetClassEQ applies the EQ predicate on the "asset_class" field.
func AssetClassEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldAssetClass, v))
}

// AssetClassNEQ applies the NEQ predicate on the "asset_class" field.
func AssetClassNEQ(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldAssetClass, v))
}

// AssetClassIn applies the In predicate on the "asset_class" field.
func AssetClassIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldAssetClass, vs...))
}

// AssetClassNotIn applies the NotIn predicate on the "asset_class" field.
func AssetClassNotIn(vs ...string) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldAssetClass, vs...))
}

// AssetClassGT applies the GT predicate on the "asset_class" field.
func AssetClassGT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldAssetClass, v))
}

// AssetClassGTE applies the GTE predicate on the "asset_class" field.
func AssetClassGTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldAssetClass, v))
}

// AssetClassLT applies the LT predicate on the "asset_class" field.
func AssetClassLT(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldAssetClass, v))
}

// AssetClassLTE applies the LTE predicate on the "asset_class" field.
func AssetClassLTE(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldAssetClass, v))
}

// AssetClassContains applies the Contains predicate on the "asset_class" field.
func AssetClassContains(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContains(FieldAssetClass, v))
}

// AssetClassHasPrefix applies the HasPrefix predicate on the "asset_class" field.
func AssetClassHasPrefix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasPrefix(FieldAssetClass, v))
}

// AssetClassHasSuffix applies the HasSuffix predicate on the "asset_class" field.
func AssetClassHasSuffix(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldHasSuffix(FieldAssetClass, v))
}

// AssetClassIsNil applies the IsNil predicate on the "asset_class" field.
func AssetClassIsNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldIsNull(FieldAssetClass))
}

// AssetClassNotNil applies the NotNil predicate on the "asset_class" field.
func AssetClassNotNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldNotNull(FieldAssetClass))
}

// AssetClassEqualFold applies the EqualFold predicate on the "asset_class" field.
func AssetClassEqualFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldEqualFold(FieldAssetClass, v))
}

// AssetClassContainsFold applies the ContainsFold predicate on the "asset_class" field.
func AssetClassContainsFold(v string) predicate.Instrument {
	return predicate.Instrument(sql.FieldContainsFold(FieldAssetClass, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldIsActive, v))
}

// DividerEQ applies the EQ predicate on the "divider" field.
func DividerEQ(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldDivider, v))
}

// DividerNEQ applies the NEQ predicate on the "divider" field.
func DividerNEQ(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldDivider, v))
}

// DividerIn applies the In predicate on the "divider" field.
func DividerIn(vs ...int) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldDivider, vs...))
}

// DividerNotIn applies the NotIn predicate on the "divider" field.
func DividerNotIn(vs ...int) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldDivider, vs...))
}

// DividerGT applies the GT predicate on the "divider" field.
func DividerGT(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldDivider, v))
}

// DividerGTE applies the GTE predicate on the "divider" field.
func DividerGTE(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldDivider, v))
}

// DividerLT applies the LT predicate on the "divider" field.
func DividerLT(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldDivider, v))
}

// DividerLTE applies the LTE predicate on the "divider" field.
func DividerLTE(v int) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldDivider, v))
}

// DividerIsNil applies the IsNil predicate on the "divider" field.
func DividerIsNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldIsNull(FieldDivider))
}

// DividerNotNil applies the NotNil predicate on the "divider" field.
func DividerNotNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldNotNull(FieldDivider))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Instrument {
	return predicate.Instrument(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Instrument {
	return predicate.Instrument(sql.FieldNotNull(FieldStartDate))
}

// IsPauseEQ applies the EQ predicate on the "is_pause" field.
func IsPauseEQ(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldEQ(FieldIsPause, v))
}

// IsPauseNEQ applies the NEQ predicate on the "is_pause" field.
func IsPauseNEQ(v bool) predicate.Instrument {
	return predicate.Instrument(sql.FieldNEQ(FieldIsPause, v))
}

// HasStates applies the HasEdge predicate on the "states" edge.
func HasStates() predicate.Instrument {
	return predicate.Instrument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatesTable, StatesColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.State
		step.Edge.Schema = schemaConfig.State
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatesWith applies the HasEdge predicate on the "states" edge with a given conditions (other predicates).
func HasStatesWith(preds ...predicate.State) predicate.Instrument {
	return predicate.Instrument(func(s *sql.Selector) {
		step := newStatesStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.State
		step.Edge.Schema = schemaConfig.State
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyncTasks applies the HasEdge predicate on the "sync_tasks" edge.
func HasSyncTasks() predicate.Instrument {
	return predicate.Instrument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncTasksTable, SyncTasksColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.SyncTask
		step.Edge.Schema = schemaConfig.SyncTask
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncTasksWith applies the HasEdge predicate on the "sync_tasks" edge with a given conditions (other predicates).
func HasSyncTasksWith(preds ...predicate.SyncTask) predicate.Instrument {
	return predicate.Instrument(func(s *sql.Selector) {
		step := newSyncTasksStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.SyncTask
		step.Edge.Schema = schemaConfig.SyncTask
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Instrument) predicate.Instrument {
	return predicate.Instrument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Instrument) predicate.Instrument {
	return predicate.Instrument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Instrument) predicate.Instrument {
	return predicate.Instrument(sql.NotPredicates(p))
}
