// Code generated by ent, DO NOT EDIT.

package synctask

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the synctask type in the database.
	Label = "sync_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstrumentID holds the string denoting the instrument_id field in the database.
	FieldInstrumentID = "instrument_id"
	// FieldTargetDate holds the string denoting the target_date field in the database.
	FieldTargetDate = "target_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHoursCount holds the string denoting the hours_count field in the database.
	FieldHoursCount = "hours_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInstrument holds the string denoting the instrument edge name in mutations.
	EdgeInstrument = "instrument"
	// Table holds the table name of the synctask in the database.
	Table = "sync_tasks"
	// InstrumentTable is the table that holds the instrument relation/edge.
	InstrumentTable = "sync_tasks"
	// InstrumentInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	InstrumentInverseTable = "instruments"
	// InstrumentColumn is the table column denoting the instrument relation/edge.
	InstrumentColumn = "instrument_id"
)

// Columns holds all SQL columns for synctask fields.
var Columns = []string{
	FieldID,
	FieldInstrumentID,
	FieldTargetDate,
	FieldStatus,
	FieldHoursCount,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHoursCount holds the default value on creation for the "hours_count" field.
	DefaultHoursCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING   Status = "PENDING"
	StatusPROCESSED Status = "PROCESSED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusPROCESSED:
		return nil
	default:
		return fmt.Errorf("synctask: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the SyncTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstrumentID orders the results by the instrument_id field.
func ByInstrumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstrumentID, opts...).ToFunc()
}

// ByTargetDate orders the results by the target_date field.
func ByTargetDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHoursCount orders the results by the hours_count field.
func ByHoursCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoursCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInstrumentField orders the results by instrument field.
func ByInstrumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstrumentStep(), sql.OrderByField(field, opts...))
	}
}
func newInstrumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstrumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InstrumentTable, InstrumentColumn),
	)
}
