// Code generated by ent, DO NOT EDIT.

package synctask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldID, id))
}

// InstrumentID applies equality check predicate on the "instrument_id" field. It's identical to InstrumentIDEQ.
func InstrumentID(v uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldInstrumentID, v))
}

// TargetDate applies equality check predicate on the "target_date" field. It's identical to TargetDateEQ.
func TargetDate(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldTargetDate, v))
}

// HoursCount applies equality check predicate on the "hours_count" field. It's identical to HoursCountEQ.
func HoursCount(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldHoursCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldCreatedAt, v))
}

// InstrumentIDEQ applies the EQ predicate on the "instrument_id" field.
func InstrumentIDEQ(v uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldInstrumentID, v))
}

// InstrumentIDNEQ applies the NEQ predicate on the "instrument_id" field.
func InstrumentIDNEQ(v uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldInstrumentID, v))
}

// InstrumentIDIn applies the In predicate on the "instrument_id" field.
func InstrumentIDIn(vs ...uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldInstrumentID, vs...))
}

// InstrumentIDNotIn applies the NotIn predicate on the "instrument_id" field.
func InstrumentIDNotIn(vs ...uuid.UUID) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldInstrumentID, vs...))
}

// TargetDateEQ applies the EQ predicate on the "target_date" field.
func TargetDateEQ(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldTargetDate, v))
}

// TargetDateNEQ applies the NEQ predicate on the "target_date" field.
func TargetDateNEQ(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldTargetDate, v))
}

// TargetDateIn applies the In predicate on the "target_date" field.
func TargetDateIn(vs ...time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldTargetDate, vs...))
}

// TargetDateNotIn applies the NotIn predicate on the "target_date" field.
func TargetDateNotIn(vs ...time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldTargetDate, vs...))
}

// TargetDateGT applies the GT predicate on the "target_date" field.
func TargetDateGT(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldTargetDate, v))
}

// TargetDateGTE applies the GTE predicate on the "target_date" field.
func TargetDateGTE(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldTargetDate, v))
}

// TargetDateLT applies the LT predicate on the "target_date" field.
func TargetDateLT(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldTargetDate, v))
}

// TargetDateLTE applies the LTE predicate on the "target_date" field.
func TargetDateLTE(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldTargetDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldStatus, vs...))
}

// HoursCountEQ applies the EQ predicate on the "hours_count" field.
func HoursCountEQ(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldHoursCount, v))
}

// HoursCountNEQ applies the NEQ predicate on the "hours_count" field.
func HoursCountNEQ(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldHoursCount, v))
}

// HoursCountIn applies the In predicate on the "hours_count" field.
func HoursCountIn(vs ...int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldHoursCount, vs...))
}

// HoursCountNotIn applies the NotIn predicate on the "hours_count" field.
func HoursCountNotIn(vs ...int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldHoursCount, vs...))
}

// HoursCountGT applies the GT predicate on the "hours_count" field.
func HoursCountGT(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldHoursCount, v))
}

// HoursCountGTE applies the GTE predicate on the "hours_count" field.
func HoursCountGTE(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldHoursCount, v))
}

// HoursCountLT applies the LT predicate on the "hours_count" field.
func HoursCountLT(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldHoursCount, v))
}

// HoursCountLTE applies the LTE predicate on the "hours_count" field.
func HoursCountLTE(v int) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldHoursCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SyncTask {
	return predicate.SyncTask(sql.FieldLTE(FieldCreatedAt, v))
}

// HasInstrument applies the HasEdge predicate on the "instrument" edge.
func HasInstrument() predicate.SyncTask {
	return predicate.SyncTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstrumentTable, InstrumentColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.SyncTask
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstrumentWith applies the HasEdge predicate on the "instrument" edge with a given conditions (other predicates).
func HasInstrumentWith(preds ...predicate.Instrument) predicate.SyncTask {
	return predicate.SyncTask(func(s *sql.Selector) {
		step := newInstrumentStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.SyncTask
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncTask) predicate.SyncTask {
	return predicate.SyncTask(sql.NotPredicates(p))
}
