// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InstrumentsColumns holds the columns for the "instruments" table.
	InstrumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "asset_class", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "divider", Type: field.TypeInt},
		{Name: "start_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "is_pause", Type: field.TypeBool, Default: false},
	}
	// InstrumentsTable holds the schema information for the "instruments" table.
	InstrumentsTable = &schema.Table{
		Name:       "instruments",
		Columns:    InstrumentsColumns,
		PrimaryKey: []*schema.Column{InstrumentsColumns[0]},
	}
	// StatesColumns holds the columns for the "states" table.
	StatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "job_type", Type: field.TypeEnum, Enums: []string{"TICK", "CANDLE"}, SchemaType: map[string]string{"postgres": "ingestion.job_type_enum"}},
		{Name: "timestamp", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "PROCESSED", "NOT_FOUND", "FAILED", "COMPLETED", "BROKEN", "CONFIRMED", "ABANDONED"}, SchemaType: map[string]string{"postgres": "ingestion.status_enum"}},
		{Name: "previous_status", Type: field.TypeEnum, Nullable: true, Enums: []string{"PENDING", "PROCESSED", "NOT_FOUND", "FAILED", "COMPLETED", "BROKEN", "CONFIRMED", "ABANDONED"}, SchemaType: map[string]string{"postgres": "ingestion.status_enum"}},
		{Name: "is_holiday", Type: field.TypeBool, Default: false},
		{Name: "resolved_tick_count", Type: field.TypeInt, Default: 0},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "not_found_streak", Type: field.TypeInt, Default: 0},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "instrument_id", Type: field.TypeUUID},
	}
	// StatesTable holds the schema information for the "states" table.
	StatesTable = &schema.Table{
		Name:       "states",
		Columns:    StatesColumns,
		PrimaryKey: []*schema.Column{StatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "states_instruments_states",
				Columns:    []*schema.Column{StatesColumns[11]},
				RefColumns: []*schema.Column{InstrumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "state_instrument_id_timestamp_job_type",
				Unique:  true,
				Columns: []*schema.Column{StatesColumns[11], StatesColumns[2], StatesColumns[1]},
			},
		},
	}
	// SyncTasksColumns holds the columns for the "sync_tasks" table.
	SyncTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "target_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "PROCESSED"}, Default: "PENDING", SchemaType: map[string]string{"postgres": "ingestion.sync_status_enum"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "instrument_id", Type: field.TypeUUID},
	}
	// SyncTasksTable holds the schema information for the "sync_tasks" table.
	SyncTasksTable = &schema.Table{
		Name:       "sync_tasks",
		Columns:    SyncTasksColumns,
		PrimaryKey: []*schema.Column{SyncTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sync_tasks_instruments_sync_tasks",
				Columns:    []*schema.Column{SyncTasksColumns[4]},
				RefColumns: []*schema.Column{InstrumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "synctask_instrument_id_target_date",
				Unique:  true,
				Columns: []*schema.Column{SyncTasksColumns[4], SyncTasksColumns[1]},
			},
		},
	}
	// TimeframesColumns holds the columns for the "timeframes" table.
	TimeframesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "minutes", Type: field.TypeInt},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// TimeframesTable holds the schema information for the "timeframes" table.
	TimeframesTable = &schema.Table{
		Name:       "timeframes",
		Columns:    TimeframesColumns,
		PrimaryKey: []*schema.Column{TimeframesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InstrumentsTable,
		StatesTable,
		SyncTasksTable,
		TimeframesTable,
	}
)

func init() {
	InstrumentsTable.Annotation = &entsql.Annotation{
		Table: "instruments",
	}
	StatesTable.ForeignKeys[0].RefTable = InstrumentsTable
	StatesTable.Annotation = &entsql.Annotation{
		Table: "states",
	}
	SyncTasksTable.ForeignKeys[0].RefTable = InstrumentsTable
	SyncTasksTable.Annotation = &entsql.Annotation{
		Table: "sync_tasks",
	}
	TimeframesTable.Annotation = &entsql.Annotation{
		Table: "timeframes",
	}
}
