// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
	"github.com/sanjari-dev/geonera-ingestion/ent/timeframe"

	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Instrument is the client for interacting with the Instrument builders.
	Instrument *InstrumentClient
	// State is the client for interacting with the State builders.
	State *StateClient
	// SyncTask is the client for interacting with the SyncTask builders.
	SyncTask *SyncTaskClient
	// Timeframe is the client for interacting with the Timeframe builders.
	Timeframe *TimeframeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Instrument = NewInstrumentClient(c.config)
	c.State = NewStateClient(c.config)
	c.SyncTask = NewSyncTaskClient(c.config)
	c.Timeframe = NewTimeframeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		// schemaConfig contains alternative names for all tables.
		schemaConfig SchemaConfig
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.schemaConfig = DefaultSchemaConfig
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Instrument: NewInstrumentClient(cfg),
		State:      NewStateClient(cfg),
		SyncTask:   NewSyncTaskClient(cfg),
		Timeframe:  NewTimeframeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Instrument: NewInstrumentClient(cfg),
		State:      NewStateClient(cfg),
		SyncTask:   NewSyncTaskClient(cfg),
		Timeframe:  NewTimeframeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Instrument.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Instrument.Use(hooks...)
	c.State.Use(hooks...)
	c.SyncTask.Use(hooks...)
	c.Timeframe.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Instrument.Intercept(interceptors...)
	c.State.Intercept(interceptors...)
	c.SyncTask.Intercept(interceptors...)
	c.Timeframe.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *InstrumentMutation:
		return c.Instrument.mutate(ctx, m)
	case *StateMutation:
		return c.State.mutate(ctx, m)
	case *SyncTaskMutation:
		return c.SyncTask.mutate(ctx, m)
	case *TimeframeMutation:
		return c.Timeframe.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// InstrumentClient is a client for the Instrument schema.
type InstrumentClient struct {
	config
}

// NewInstrumentClient returns a client for the Instrument from the given config.
func NewInstrumentClient(c config) *InstrumentClient {
	return &InstrumentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `instrument.Hooks(f(g(h())))`.
func (c *InstrumentClient) Use(hooks ...Hook) {
	c.hooks.Instrument = append(c.hooks.Instrument, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `instrument.Intercept(f(g(h())))`.
func (c *InstrumentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Instrument = append(c.inters.Instrument, interceptors...)
}

// Create returns a builder for creating a Instrument entity.
func (c *InstrumentClient) Create() *InstrumentCreate {
	mutation := newInstrumentMutation(c.config, OpCreate)
	return &InstrumentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Instrument entities.
func (c *InstrumentClient) CreateBulk(builders ...*InstrumentCreate) *InstrumentCreateBulk {
	return &InstrumentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InstrumentClient) MapCreateBulk(slice any, setFunc func(*InstrumentCreate, int)) *InstrumentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InstrumentCreateBulk{err: fmt.Errorf("calling to InstrumentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InstrumentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InstrumentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Instrument.
func (c *InstrumentClient) Update() *InstrumentUpdate {
	mutation := newInstrumentMutation(c.config, OpUpdate)
	return &InstrumentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InstrumentClient) UpdateOne(_m *Instrument) *InstrumentUpdateOne {
	mutation := newInstrumentMutation(c.config, OpUpdateOne, withInstrument(_m))
	return &InstrumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InstrumentClient) UpdateOneID(id uuid.UUID) *InstrumentUpdateOne {
	mutation := newInstrumentMutation(c.config, OpUpdateOne, withInstrumentID(id))
	return &InstrumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Instrument.
func (c *InstrumentClient) Delete() *InstrumentDelete {
	mutation := newInstrumentMutation(c.config, OpDelete)
	return &InstrumentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InstrumentClient) DeleteOne(_m *Instrument) *InstrumentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InstrumentClient) DeleteOneID(id uuid.UUID) *InstrumentDeleteOne {
	builder := c.Delete().Where(instrument.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InstrumentDeleteOne{builder}
}

// Query returns a query builder for Instrument.
func (c *InstrumentClient) Query() *InstrumentQuery {
	return &InstrumentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInstrument},
		inters: c.Interceptors(),
	}
}

// Get returns a Instrument entity by its id.
func (c *InstrumentClient) Get(ctx context.Context, id uuid.UUID) (*Instrument, error) {
	return c.Query().Where(instrument.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InstrumentClient) GetX(ctx context.Context, id uuid.UUID) *Instrument {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStates queries the states edge of a Instrument.
func (c *InstrumentClient) QueryStates(_m *Instrument) *StateQuery {
	query := (&StateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(instrument.Table, instrument.FieldID, id),
			sqlgraph.To(state.Table, state.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instrument.StatesTable, instrument.StatesColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.State
		step.Edge.Schema = schemaConfig.State
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySyncTasks queries the sync_tasks edge of a Instrument.
func (c *InstrumentClient) QuerySyncTasks(_m *Instrument) *SyncTaskQuery {
	query := (&SyncTaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(instrument.Table, instrument.FieldID, id),
			sqlgraph.To(synctask.Table, synctask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instrument.SyncTasksTable, instrument.SyncTasksColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.SyncTask
		step.Edge.Schema = schemaConfig.SyncTask
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InstrumentClient) Hooks() []Hook {
	return c.hooks.Instrument
}

// Interceptors returns the client interceptors.
func (c *InstrumentClient) Interceptors() []Interceptor {
	return c.inters.Instrument
}

func (c *InstrumentClient) mutate(ctx context.Context, m *InstrumentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InstrumentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InstrumentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InstrumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InstrumentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Instrument mutation op: %q", m.Op())
	}
}

// StateClient is a client for the State schema.
type StateClient struct {
	config
}

// NewStateClient returns a client for the State from the given config.
func NewStateClient(c config) *StateClient {
	return &StateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `state.Hooks(f(g(h())))`.
func (c *StateClient) Use(hooks ...Hook) {
	c.hooks.State = append(c.hooks.State, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `state.Intercept(f(g(h())))`.
func (c *StateClient) Intercept(interceptors ...Interceptor) {
	c.inters.State = append(c.inters.State, interceptors...)
}

// Create returns a builder for creating a State entity.
func (c *StateClient) Create() *StateCreate {
	mutation := newStateMutation(c.config, OpCreate)
	return &StateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of State entities.
func (c *StateClient) CreateBulk(builders ...*StateCreate) *StateCreateBulk {
	return &StateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StateClient) MapCreateBulk(slice any, setFunc func(*StateCreate, int)) *StateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StateCreateBulk{err: fmt.Errorf("calling to StateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for State.
func (c *StateClient) Update() *StateUpdate {
	mutation := newStateMutation(c.config, OpUpdate)
	return &StateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StateClient) UpdateOne(_m *State) *StateUpdateOne {
	mutation := newStateMutation(c.config, OpUpdateOne, withState(_m))
	return &StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StateClient) UpdateOneID(id uuid.UUID) *StateUpdateOne {
	mutation := newStateMutation(c.config, OpUpdateOne, withStateID(id))
	return &StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for State.
func (c *StateClient) Delete() *StateDelete {
	mutation := newStateMutation(c.config, OpDelete)
	return &StateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StateClient) DeleteOne(_m *State) *StateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StateClient) DeleteOneID(id uuid.UUID) *StateDeleteOne {
	builder := c.Delete().Where(state.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StateDeleteOne{builder}
}

// Query returns a query builder for State.
func (c *StateClient) Query() *StateQuery {
	return &StateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeState},
		inters: c.Interceptors(),
	}
}

// Get returns a State entity by its id.
func (c *StateClient) Get(ctx context.Context, id uuid.UUID) (*State, error) {
	return c.Query().Where(state.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StateClient) GetX(ctx context.Context, id uuid.UUID) *State {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstrument queries the instrument edge of a State.
func (c *StateClient) QueryInstrument(_m *State) *InstrumentQuery {
	query := (&InstrumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(state.Table, state.FieldID, id),
			sqlgraph.To(instrument.Table, instrument.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, state.InstrumentTable, state.InstrumentColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.State
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StateClient) Hooks() []Hook {
	return c.hooks.State
}

// Interceptors returns the client interceptors.
func (c *StateClient) Interceptors() []Interceptor {
	return c.inters.State
}

func (c *StateClient) mutate(ctx context.Context, m *StateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown State mutation op: %q", m.Op())
	}
}

// SyncTaskClient is a client for the SyncTask schema.
type SyncTaskClient struct {
	config
}

// NewSyncTaskClient returns a client for the SyncTask from the given config.
func NewSyncTaskClient(c config) *SyncTaskClient {
	return &SyncTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `synctask.Hooks(f(g(h())))`.
func (c *SyncTaskClient) Use(hooks ...Hook) {
	c.hooks.SyncTask = append(c.hooks.SyncTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `synctask.Intercept(f(g(h())))`.
func (c *SyncTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncTask = append(c.inters.SyncTask, interceptors...)
}

// Create returns a builder for creating a SyncTask entity.
func (c *SyncTaskClient) Create() *SyncTaskCreate {
	mutation := newSyncTaskMutation(c.config, OpCreate)
	return &SyncTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncTask entities.
func (c *SyncTaskClient) CreateBulk(builders ...*SyncTaskCreate) *SyncTaskCreateBulk {
	return &SyncTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncTaskClient) MapCreateBulk(slice any, setFunc func(*SyncTaskCreate, int)) *SyncTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncTaskCreateBulk{err: fmt.Errorf("calling to SyncTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncTask.
func (c *SyncTaskClient) Update() *SyncTaskUpdate {
	mutation := newSyncTaskMutation(c.config, OpUpdate)
	return &SyncTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncTaskClient) UpdateOne(_m *SyncTask) *SyncTaskUpdateOne {
	mutation := newSyncTaskMutation(c.config, OpUpdateOne, withSyncTask(_m))
	return &SyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncTaskClient) UpdateOneID(id uuid.UUID) *SyncTaskUpdateOne {
	mutation := newSyncTaskMutation(c.config, OpUpdateOne, withSyncTaskID(id))
	return &SyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncTask.
func (c *SyncTaskClient) Delete() *SyncTaskDelete {
	mutation := newSyncTaskMutation(c.config, OpDelete)
	return &SyncTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncTaskClient) DeleteOne(_m *SyncTask) *SyncTaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncTaskClient) DeleteOneID(id uuid.UUID) *SyncTaskDeleteOne {
	builder := c.Delete().Where(synctask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncTaskDeleteOne{builder}
}

// Query returns a query builder for SyncTask.
func (c *SyncTaskClient) Query() *SyncTaskQuery {
	return &SyncTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncTask},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncTask entity by its id.
func (c *SyncTaskClient) Get(ctx context.Context, id uuid.UUID) (*SyncTask, error) {
	return c.Query().Where(synctask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncTaskClient) GetX(ctx context.Context, id uuid.UUID) *SyncTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInstrument queries the instrument edge of a SyncTask.
func (c *SyncTaskClient) QueryInstrument(_m *SyncTask) *InstrumentQuery {
	query := (&InstrumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(synctask.Table, synctask.FieldID, id),
			sqlgraph.To(instrument.Table, instrument.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, synctask.InstrumentTable, synctask.InstrumentColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.SyncTask
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SyncTaskClient) Hooks() []Hook {
	return c.hooks.SyncTask
}

// Interceptors returns the client interceptors.
func (c *SyncTaskClient) Interceptors() []Interceptor {
	return c.inters.SyncTask
}

func (c *SyncTaskClient) mutate(ctx context.Context, m *SyncTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncTask mutation op: %q", m.Op())
	}
}

// TimeframeClient is a client for the Timeframe schema.
type TimeframeClient struct {
	config
}

// NewTimeframeClient returns a client for the Timeframe from the given config.
func NewTimeframeClient(c config) *TimeframeClient {
	return &TimeframeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `timeframe.Hooks(f(g(h())))`.
func (c *TimeframeClient) Use(hooks ...Hook) {
	c.hooks.Timeframe = append(c.hooks.Timeframe, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `timeframe.Intercept(f(g(h())))`.
func (c *TimeframeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Timeframe = append(c.inters.Timeframe, interceptors...)
}

// Create returns a builder for creating a Timeframe entity.
func (c *TimeframeClient) Create() *TimeframeCreate {
	mutation := newTimeframeMutation(c.config, OpCreate)
	return &TimeframeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Timeframe entities.
func (c *TimeframeClient) CreateBulk(builders ...*TimeframeCreate) *TimeframeCreateBulk {
	return &TimeframeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TimeframeClient) MapCreateBulk(slice any, setFunc func(*TimeframeCreate, int)) *TimeframeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TimeframeCreateBulk{err: fmt.Errorf("calling to TimeframeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TimeframeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TimeframeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Timeframe.
func (c *TimeframeClient) Update() *TimeframeUpdate {
	mutation := newTimeframeMutation(c.config, OpUpdate)
	return &TimeframeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TimeframeClient) UpdateOne(_m *Timeframe) *TimeframeUpdateOne {
	mutation := newTimeframeMutation(c.config, OpUpdateOne, withTimeframe(_m))
	return &TimeframeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TimeframeClient) UpdateOneID(id uuid.UUID) *TimeframeUpdateOne {
	mutation := newTimeframeMutation(c.config, OpUpdateOne, withTimeframeID(id))
	return &TimeframeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Timeframe.
func (c *TimeframeClient) Delete() *TimeframeDelete {
	mutation := newTimeframeMutation(c.config, OpDelete)
	return &TimeframeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TimeframeClient) DeleteOne(_m *Timeframe) *TimeframeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TimeframeClient) DeleteOneID(id uuid.UUID) *TimeframeDeleteOne {
	builder := c.Delete().Where(timeframe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TimeframeDeleteOne{builder}
}

// Query returns a query builder for Timeframe.
func (c *TimeframeClient) Query() *TimeframeQuery {
	return &TimeframeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTimeframe},
		inters: c.Interceptors(),
	}
}

// Get returns a Timeframe entity by its id.
func (c *TimeframeClient) Get(ctx context.Context, id uuid.UUID) (*Timeframe, error) {
	return c.Query().Where(timeframe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TimeframeClient) GetX(ctx context.Context, id uuid.UUID) *Timeframe {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TimeframeClient) Hooks() []Hook {
	return c.hooks.Timeframe
}

// Interceptors returns the client interceptors.
func (c *TimeframeClient) Interceptors() []Interceptor {
	return c.inters.Timeframe
}

func (c *TimeframeClient) mutate(ctx context.Context, m *TimeframeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TimeframeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TimeframeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TimeframeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TimeframeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Timeframe mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Instrument, State, SyncTask, Timeframe []ent.Hook
	}
	inters struct {
		Instrument, State, SyncTask, Timeframe []ent.Interceptor
	}
)

var (
	// DefaultSchemaConfig represents the default schema names for all tables as defined in ent/schema.
	DefaultSchemaConfig = SchemaConfig{
		Instrument: tableSchemas[1],
		State:      tableSchemas[0],
		SyncTask:   tableSchemas[0],
		Timeframe:  tableSchemas[1],
	}
	tableSchemas = [...]string{"ingestion", "master"}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *config) {
		c.schemaConfig = schemaConfig
	}
}
