// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
)

// InstrumentUpdate is the builder for updating Instrument entities.
type InstrumentUpdate struct {
	config
	hooks    []Hook
	mutation *InstrumentMutation
}

// Where appends a list predicates to the InstrumentUpdate builder.
func (_u *InstrumentUpdate) Where(ps ...predicate.Instrument) *InstrumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *InstrumentUpdate) SetName(v string) *InstrumentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableName(v *string) *InstrumentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *InstrumentUpdate) SetDescription(v string) *InstrumentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableDescription(v *string) *InstrumentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAssetClass sets the "asset_class" field.
func (_u *InstrumentUpdate) SetAssetClass(v string) *InstrumentUpdate {
	_u.mutation.SetAssetClass(v)
	return _u
}

// SetNillableAssetClass sets the "asset_class" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableAssetClass(v *string) *InstrumentUpdate {
	if v != nil {
		_u.SetAssetClass(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *InstrumentUpdate) SetIsActive(v bool) *InstrumentUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableIsActive(v *bool) *InstrumentUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDivider sets the "divider" field.
func (_u *InstrumentUpdate) SetDivider(v int) *InstrumentUpdate {
	_u.mutation.ResetDivider()
	_u.mutation.SetDivider(v)
	return _u
}

// SetNillableDivider sets the "divider" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableDivider(v *int) *InstrumentUpdate {
	if v != nil {
		_u.SetDivider(*v)
	}
	return _u
}

// AddDivider adds value to the "divider" field.
func (_u *InstrumentUpdate) AddDivider(v int) *InstrumentUpdate {
	_u.mutation.AddDivider(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *InstrumentUpdate) SetStartDate(v time.Time) *InstrumentUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableStartDate(v *time.Time) *InstrumentUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetIsPause sets the "is_pause" field.
func (_u *InstrumentUpdate) SetIsPause(v bool) *InstrumentUpdate {
	_u.mutation.SetIsPause(v)
	return _u
}

// SetNillableIsPause sets the "is_pause" field if the given value is not nil.
func (_u *InstrumentUpdate) SetNillableIsPause(v *bool) *InstrumentUpdate {
	if v != nil {
		_u.SetIsPause(*v)
	}
	return _u
}

// AddStateIDs adds the "states" edge to the State entity by IDs.
func (_u *InstrumentUpdate) AddStateIDs(ids ...uuid.UUID) *InstrumentUpdate {
	_u.mutation.AddStateIDs(ids...)
	return _u
}

// AddStates adds the "states" edges to the State entity.
func (_u *InstrumentUpdate) AddStates(v ...*State) *InstrumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStateIDs(ids...)
}

// AddSyncTaskIDs adds the "sync_tasks" edge to the SyncTask entity by IDs.
func (_u *InstrumentUpdate) AddSyncTaskIDs(ids ...uuid.UUID) *InstrumentUpdate {
	_u.mutation.AddSyncTaskIDs(ids...)
	return _u
}

// AddSyncTasks adds the "sync_tasks" edges to the SyncTask entity.
func (_u *InstrumentUpdate) AddSyncTasks(v ...*SyncTask) *InstrumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncTaskIDs(ids...)
}

// Mutation returns the InstrumentMutation object of the builder.
func (_u *InstrumentUpdate) Mutation() *InstrumentMutation {
	return _u.mutation
}

// ClearStates clears all "states" edges to the State entity.
func (_u *InstrumentUpdate) ClearStates() *InstrumentUpdate {
	_u.mutation.ClearStates()
	return _u
}

// RemoveStateIDs removes the "states" edge to State entities by IDs.
func (_u *InstrumentUpdate) RemoveStateIDs(ids ...uuid.UUID) *InstrumentUpdate {
	_u.mutation.RemoveStateIDs(ids...)
	return _u
}

// RemoveStates removes "states" edges to State entities.
func (_u *InstrumentUpdate) RemoveStates(v ...*State) *InstrumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStateIDs(ids...)
}

// ClearSyncTasks clears all "sync_tasks" edges to the SyncTask entity.
func (_u *InstrumentUpdate) ClearSyncTasks() *InstrumentUpdate {
	_u.mutation.ClearSyncTasks()
	return _u
}

// RemoveSyncTaskIDs removes the "sync_tasks" edge to SyncTask entities by IDs.
func (_u *InstrumentUpdate) RemoveSyncTaskIDs(ids ...uuid.UUID) *InstrumentUpdate {
	_u.mutation.RemoveSyncTaskIDs(ids...)
	return _u
}

// RemoveSyncTasks removes "sync_tasks" edges to SyncTask entities.
func (_u *InstrumentUpdate) RemoveSyncTasks(v ...*SyncTask) *InstrumentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstrumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstrumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstrumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstrumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstrumentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := instrument.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instrument.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := instrument.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Instrument.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetClass(); ok {
		if err := instrument.AssetClassValidator(v); err != nil {
			return &ValidationError{Name: "asset_class", err: fmt.Errorf(`ent: validator failed for field "Instrument.asset_class": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Divider(); ok {
		if err := instrument.DividerValidator(v); err != nil {
			return &ValidationError{Name: "divider", err: fmt.Errorf(`ent: validator failed for field "Instrument.divider": %w`, err)}
		}
	}
	return nil
}

func (_u *InstrumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instrument.Table, instrument.Columns, sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(instrument.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(instrument.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetClass(); ok {
		_spec.SetField(instrument.FieldAssetClass, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(instrument.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Divider(); ok {
		_spec.SetField(instrument.FieldDivider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivider(); ok {
		_spec.AddField(instrument.FieldDivider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(instrument.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsPause(); ok {
		_spec.SetField(instrument.FieldIsPause, field.TypeBool, value)
	}
	if _u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatesIDs(); len(nodes) > 0 && !_u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncTasksIDs(); len(nodes) > 0 && !_u.mutation.SyncTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Instrument
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instrument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstrumentUpdateOne is the builder for updating a single Instrument entity.
type InstrumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstrumentMutation
}

// SetName sets the "name" field.
func (_u *InstrumentUpdateOne) SetName(v string) *InstrumentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableName(v *string) *InstrumentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *InstrumentUpdateOne) SetDescription(v string) *InstrumentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableDescription(v *string) *InstrumentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAssetClass sets the "asset_class" field.
func (_u *InstrumentUpdateOne) SetAssetClass(v string) *InstrumentUpdateOne {
	_u.mutation.SetAssetClass(v)
	return _u
}

// SetNillableAssetClass sets the "asset_class" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableAssetClass(v *string) *InstrumentUpdateOne {
	if v != nil {
		_u.SetAssetClass(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *InstrumentUpdateOne) SetIsActive(v bool) *InstrumentUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableIsActive(v *bool) *InstrumentUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDivider sets the "divider" field.
func (_u *InstrumentUpdateOne) SetDivider(v int) *InstrumentUpdateOne {
	_u.mutation.ResetDivider()
	_u.mutation.SetDivider(v)
	return _u
}

// SetNillableDivider sets the "divider" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableDivider(v *int) *InstrumentUpdateOne {
	if v != nil {
		_u.SetDivider(*v)
	}
	return _u
}

// AddDivider adds value to the "divider" field.
func (_u *InstrumentUpdateOne) AddDivider(v int) *InstrumentUpdateOne {
	_u.mutation.AddDivider(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *InstrumentUpdateOne) SetStartDate(v time.Time) *InstrumentUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableStartDate(v *time.Time) *InstrumentUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetIsPause sets the "is_pause" field.
func (_u *InstrumentUpdateOne) SetIsPause(v bool) *InstrumentUpdateOne {
	_u.mutation.SetIsPause(v)
	return _u
}

// SetNillableIsPause sets the "is_pause" field if the given value is not nil.
func (_u *InstrumentUpdateOne) SetNillableIsPause(v *bool) *InstrumentUpdateOne {
	if v != nil {
		_u.SetIsPause(*v)
	}
	return _u
}

// AddStateIDs adds the "states" edge to the State entity by IDs.
func (_u *InstrumentUpdateOne) AddStateIDs(ids ...uuid.UUID) *InstrumentUpdateOne {
	_u.mutation.AddStateIDs(ids...)
	return _u
}

// AddStates adds the "states" edges to the State entity.
func (_u *InstrumentUpdateOne) AddStates(v ...*State) *InstrumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStateIDs(ids...)
}

// AddSyncTaskIDs adds the "sync_tasks" edge to the SyncTask entity by IDs.
func (_u *InstrumentUpdateOne) AddSyncTaskIDs(ids ...uuid.UUID) *InstrumentUpdateOne {
	_u.mutation.AddSyncTaskIDs(ids...)
	return _u
}

// AddSyncTasks adds the "sync_tasks" edges to the SyncTask entity.
func (_u *InstrumentUpdateOne) AddSyncTasks(v ...*SyncTask) *InstrumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncTaskIDs(ids...)
}

// Mutation returns the InstrumentMutation object of the builder.
func (_u *InstrumentUpdateOne) Mutation() *InstrumentMutation {
	return _u.mutation
}

// ClearStates clears all "states" edges to the State entity.
func (_u *InstrumentUpdateOne) ClearStates() *InstrumentUpdateOne {
	_u.mutation.ClearStates()
	return _u
}

// RemoveStateIDs removes the "states" edge to State entities by IDs.
func (_u *InstrumentUpdateOne) RemoveStateIDs(ids ...uuid.UUID) *InstrumentUpdateOne {
	_u.mutation.RemoveStateIDs(ids...)
	return _u
}

// RemoveStates removes "states" edges to State entities.
func (_u *InstrumentUpdateOne) RemoveStates(v ...*State) *InstrumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStateIDs(ids...)
}

// ClearSyncTasks clears all "sync_tasks" edges to the SyncTask entity.
func (_u *InstrumentUpdateOne) ClearSyncTasks() *InstrumentUpdateOne {
	_u.mutation.ClearSyncTasks()
	return _u
}

// RemoveSyncTaskIDs removes the "sync_tasks" edge to SyncTask entities by IDs.
func (_u *InstrumentUpdateOne) RemoveSyncTaskIDs(ids ...uuid.UUID) *InstrumentUpdateOne {
	_u.mutation.RemoveSyncTaskIDs(ids...)
	return _u
}

// RemoveSyncTasks removes "sync_tasks" edges to SyncTask entities.
func (_u *InstrumentUpdateOne) RemoveSyncTasks(v ...*SyncTask) *InstrumentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncTaskIDs(ids...)
}

// Where appends a list predicates to the InstrumentUpdate builder.
func (_u *InstrumentUpdateOne) Where(ps ...predicate.Instrument) *InstrumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstrumentUpdateOne) Select(field string, fields ...string) *InstrumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Instrument entity.
func (_u *InstrumentUpdateOne) Save(ctx context.Context) (*Instrument, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstrumentUpdateOne) SaveX(ctx context.Context) *Instrument {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstrumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstrumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstrumentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := instrument.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instrument.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := instrument.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Instrument.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AssetClass(); ok {
		if err := instrument.AssetClassValidator(v); err != nil {
			return &ValidationError{Name: "asset_class", err: fmt.Errorf(`ent: validator failed for field "Instrument.asset_class": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Divider(); ok {
		if err := instrument.DividerValidator(v); err != nil {
			return &ValidationError{Name: "divider", err: fmt.Errorf(`ent: validator failed for field "Instrument.divider": %w`, err)}
		}
	}
	return nil
}

func (_u *InstrumentUpdateOne) sqlSave(ctx context.Context) (_node *Instrument, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instrument.Table, instrument.Columns, sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Instrument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instrument.FieldID)
		for _, f := range fields {
			if !instrument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instrument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(instrument.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(instrument.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssetClass(); ok {
		_spec.SetField(instrument.FieldAssetClass, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(instrument.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Divider(); ok {
		_spec.SetField(instrument.FieldDivider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivider(); ok {
		_spec.AddField(instrument.FieldDivider, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(instrument.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsPause(); ok {
		_spec.SetField(instrument.FieldIsPause, field.TypeBool, value)
	}
	if _u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatesIDs(); len(nodes) > 0 && !_u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncTasksIDs(); len(nodes) > 0 && !_u.mutation.SyncTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Instrument
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Instrument{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instrument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
