// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
)

// InstrumentCreate is the builder for creating a Instrument entity.
type InstrumentCreate struct {
	config
	mutation *InstrumentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *InstrumentCreate) SetName(v string) *InstrumentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *InstrumentCreate) SetDescription(v string) *InstrumentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableDescription(v *string) *InstrumentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetAssetClass sets the "asset_class" field.
func (_c *InstrumentCreate) SetAssetClass(v string) *InstrumentCreate {
	_c.mutation.SetAssetClass(v)
	return _c
}

// SetNillableAssetClass sets the "asset_class" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableAssetClass(v *string) *InstrumentCreate {
	if v != nil {
		_c.SetAssetClass(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *InstrumentCreate) SetIsActive(v bool) *InstrumentCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableIsActive(v *bool) *InstrumentCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetDivider sets the "divider" field.
func (_c *InstrumentCreate) SetDivider(v int) *InstrumentCreate {
	_c.mutation.SetDivider(v)
	return _c
}

// SetNillableDivider sets the "divider" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableDivider(v *int) *InstrumentCreate {
	if v != nil {
		_c.SetDivider(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *InstrumentCreate) SetStartDate(v time.Time) *InstrumentCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableStartDate(v *time.Time) *InstrumentCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetIsPause sets the "is_pause" field.
func (_c *InstrumentCreate) SetIsPause(v bool) *InstrumentCreate {
	_c.mutation.SetIsPause(v)
	return _c
}

// SetNillableIsPause sets the "is_pause" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableIsPause(v *bool) *InstrumentCreate {
	if v != nil {
		_c.SetIsPause(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InstrumentCreate) SetID(v uuid.UUID) *InstrumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InstrumentCreate) SetNillableID(v *uuid.UUID) *InstrumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddStateIDs adds the "states" edge to the State entity by IDs.
func (_c *InstrumentCreate) AddStateIDs(ids ...uuid.UUID) *InstrumentCreate {
	_c.mutation.AddStateIDs(ids...)
	return _c
}

// AddStates adds the "states" edges to the State entity.
func (_c *InstrumentCreate) AddStates(v ...*State) *InstrumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStateIDs(ids...)
}

// AddSyncTaskIDs adds the "sync_tasks" edge to the SyncTask entity by IDs.
func (_c *InstrumentCreate) AddSyncTaskIDs(ids ...uuid.UUID) *InstrumentCreate {
	_c.mutation.AddSyncTaskIDs(ids...)
	return _c
}

// AddSyncTasks adds the "sync_tasks" edges to the SyncTask entity.
func (_c *InstrumentCreate) AddSyncTasks(v ...*SyncTask) *InstrumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyncTaskIDs(ids...)
}

// Mutation returns the InstrumentMutation object of the builder.
func (_c *InstrumentCreate) Mutation() *InstrumentMutation {
	return _c.mutation
}

// Save creates the Instrument in the database.
func (_c *InstrumentCreate) Save(ctx context.Context) (*Instrument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstrumentCreate) SaveX(ctx context.Context) *Instrument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstrumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstrumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstrumentCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := instrument.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.IsPause(); !ok {
		v := instrument.DefaultIsPause
		_c.mutation.SetIsPause(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := instrument.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstrumentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Instrument.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := instrument.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instrument.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Instrument.is_active"`)}
	}
	if _, ok := _c.mutation.IsPause(); !ok {
		return &ValidationError{Name: "is_pause", err: errors.New(`ent: missing required field "Instrument.is_pause"`)}
	}
	return nil
}

func (_c *InstrumentCreate) sqlSave(ctx context.Context) (*Instrument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstrumentCreate) createSpec() (*Instrument, *sqlgraph.CreateSpec) {
	var (
		_node = &Instrument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(instrument.Table, sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Instrument
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(instrument.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(instrument.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.AssetClass(); ok {
		_spec.SetField(instrument.FieldAssetClass, field.TypeString, value)
		_node.AssetClass = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(instrument.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.Divider(); ok {
		_spec.SetField(instrument.FieldDivider, field.TypeInt, value)
		_node.Divider = &value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(instrument.FieldStartDate, field.TypeTime, value)
		_node.StartDate = &value
	}
	if value, ok := _c.mutation.IsPause(); ok {
		_spec.SetField(instrument.FieldIsPause, field.TypeBool, value)
		_node.IsPause = value
	}
	if nodes := _c.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.StatesTable,
			Columns: []string{instrument.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SyncTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   instrument.SyncTasksTable,
			Columns: []string{instrument.SyncTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InstrumentCreateBulk is the builder for creating many Instrument entities in bulk.
type InstrumentCreateBulk struct {
	config
	err      error
	builders []*InstrumentCreate
}

// Save creates the Instrument entities in the database.
func (_c *InstrumentCreateBulk) Save(ctx context.Context) ([]*Instrument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Instrument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstrumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstrumentCreateBulk) SaveX(ctx context.Context) []*Instrument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstrumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstrumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
