// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
)

// Instrument is the model entity for the Instrument schema.
type Instrument struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// AssetClass holds the value of the "asset_class" field.
	AssetClass *string `json:"asset_class,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Divider holds the value of the "divider" field.
	Divider *int `json:"divider,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// IsPause holds the value of the "is_pause" field.
	IsPause bool `json:"is_pause,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InstrumentQuery when eager-loading is set.
	Edges        InstrumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InstrumentEdges holds the relations/edges for other nodes in the graph.
type InstrumentEdges struct {
	// States holds the value of the states edge.
	States []*State `json:"states,omitempty"`
	// SyncTasks holds the value of the sync_tasks edge.
	SyncTasks []*SyncTask `json:"sync_tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// StatesOrErr returns the States value or an error if the edge
// was not loaded in eager-loading.
func (e InstrumentEdges) StatesOrErr() ([]*State, error) {
	if e.loadedTypes[0] {
		return e.States, nil
	}
	return nil, &NotLoadedError{edge: "states"}
}

// SyncTasksOrErr returns the SyncTasks value or an error if the edge
// was not loaded in eager-loading.
func (e InstrumentEdges) SyncTasksOrErr() ([]*SyncTask, error) {
	if e.loadedTypes[1] {
		return e.SyncTasks, nil
	}
	return nil, &NotLoadedError{edge: "sync_tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Instrument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case instrument.FieldIsActive, instrument.FieldIsPause:
			values[i] = new(sql.NullBool)
		case instrument.FieldDivider:
			values[i] = new(sql.NullInt64)
		case instrument.FieldName, instrument.FieldDescription, instrument.FieldAssetClass:
			values[i] = new(sql.NullString)
		case instrument.FieldStartDate:
			values[i] = new(sql.NullTime)
		case instrument.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Instrument fields.
func (_m *Instrument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case instrument.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case instrument.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case instrument.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case instrument.FieldAssetClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_class", values[i])
			} else if value.Valid {
				_m.AssetClass = new(string)
				*_m.AssetClass = value.String
			}
		case instrument.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case instrument.FieldDivider:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field divider", values[i])
			} else if value.Valid {
				_m.Divider = new(int)
				*_m.Divider = int(value.Int64)
			}
		case instrument.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case instrument.FieldIsPause:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_pause", values[i])
			} else if value.Valid {
				_m.IsPause = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Instrument.
// This includes values selected through modifiers, order, etc.
func (_m *Instrument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStates queries the "states" edge of the Instrument entity.
func (_m *Instrument) QueryStates() *StateQuery {
	return NewInstrumentClient(_m.config).QueryStates(_m)
}

// QuerySyncTasks queries the "sync_tasks" edge of the Instrument entity.
func (_m *Instrument) QuerySyncTasks() *SyncTaskQuery {
	return NewInstrumentClient(_m.config).QuerySyncTasks(_m)
}

// Update returns a builder for updating this Instrument.
// Note that you need to call Instrument.Unwrap() before calling this method if this Instrument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Instrument) Update() *InstrumentUpdateOne {
	return NewInstrumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Instrument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Instrument) Unwrap() *Instrument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Instrument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Instrument) String() string {
	var builder strings.Builder
	builder.WriteString("Instrument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AssetClass; v != nil {
		builder.WriteString("asset_class=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.Divider; v != nil {
		builder.WriteString("divider=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_pause=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPause))
	builder.WriteByte(')')
	return builder.String()
}

// Instruments is a parsable slice of Instrument.
type Instruments []*Instrument
