// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
	"github.com/sanjari-dev/geonera-ingestion/ent/timeframe"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeInstrument = "Instrument"
	TypeState      = "State"
	TypeSyncTask   = "SyncTask"
	TypeTimeframe  = "Timeframe"
)

// InstrumentMutation represents an operation that mutates the Instrument nodes in the graph.
type InstrumentMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	name              *string
	description       *string
	asset_class       *string
	is_active         *bool
	divider           *int
	adddivider        *int
	start_date        *time.Time
	is_pause          *bool
	clearedFields     map[string]struct{}
	states            map[uuid.UUID]struct{}
	removedstates     map[uuid.UUID]struct{}
	clearedstates     bool
	sync_tasks        map[uuid.UUID]struct{}
	removedsync_tasks map[uuid.UUID]struct{}
	clearedsync_tasks bool
	done              bool
	oldValue          func(context.Context) (*Instrument, error)
	predicates        []predicate.Instrument
}

var _ ent.Mutation = (*InstrumentMutation)(nil)

// instrumentOption allows management of the mutation configuration using functional options.
type instrumentOption func(*InstrumentMutation)

// newInstrumentMutation creates new mutation for the Instrument entity.
func newInstrumentMutation(c config, op Op, opts ...instrumentOption) *InstrumentMutation {
	m := &InstrumentMutation{
		config:        c,
		op:            op,
		typ:           TypeInstrument,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withInstrumentID sets the ID field of the mutation.
func withInstrumentID(id uuid.UUID) instrumentOption {
	return func(m *InstrumentMutation) {
		var (
			err   error
			once  sync.Once
			value *Instrument
		)
		m.oldValue = func(ctx context.Context) (*Instrument, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Instrument.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withInstrument sets the old Instrument of the mutation.
func withInstrument(node *Instrument) instrumentOption {
	return func(m *InstrumentMutation) {
		m.oldValue = func(context.Context) (*Instrument, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m InstrumentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m InstrumentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Instrument entities.
func (m *InstrumentMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *InstrumentMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *InstrumentMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Instrument.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *InstrumentMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *InstrumentMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *InstrumentMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *InstrumentMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *InstrumentMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldDescription(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *InstrumentMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[instrument.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *InstrumentMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[instrument.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *InstrumentMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, instrument.FieldDescription)
}

// SetAssetClass sets the "asset_class" field.
func (m *InstrumentMutation) SetAssetClass(s string) {
	m.asset_class = &s
}

// AssetClass returns the value of the "asset_class" field in the mutation.
func (m *InstrumentMutation) AssetClass() (r string, exists bool) {
	v := m.asset_class
	if v == nil {
		return
	}
	return *v, true
}

// OldAssetClass returns the old "asset_class" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldAssetClass(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAssetClass is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAssetClass requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAssetClass: %w", err)
	}
	return oldValue.AssetClass, nil
}

// ClearAssetClass clears the value of the "asset_class" field.
func (m *InstrumentMutation) ClearAssetClass() {
	m.asset_class = nil
	m.clearedFields[instrument.FieldAssetClass] = struct{}{}
}

// AssetClassCleared returns if the "asset_class" field was cleared in this mutation.
func (m *InstrumentMutation) AssetClassCleared() bool {
	_, ok := m.clearedFields[instrument.FieldAssetClass]
	return ok
}

// ResetAssetClass resets all changes to the "asset_class" field.
func (m *InstrumentMutation) ResetAssetClass() {
	m.asset_class = nil
	delete(m.clearedFields, instrument.FieldAssetClass)
}

// SetIsActive sets the "is_active" field.
func (m *InstrumentMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *InstrumentMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *InstrumentMutation) ResetIsActive() {
	m.is_active = nil
}

// SetDivider sets the "divider" field.
func (m *InstrumentMutation) SetDivider(i int) {
	m.divider = &i
	m.adddivider = nil
}

// Divider returns the value of the "divider" field in the mutation.
func (m *InstrumentMutation) Divider() (r int, exists bool) {
	v := m.divider
	if v == nil {
		return
	}
	return *v, true
}

// OldDivider returns the old "divider" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldDivider(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDivider is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDivider requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDivider: %w", err)
	}
	return oldValue.Divider, nil
}

// AddDivider adds i to the "divider" field.
func (m *InstrumentMutation) AddDivider(i int) {
	if m.adddivider != nil {
		*m.adddivider += i
	} else {
		m.adddivider = &i
	}
}

// AddedDivider returns the value that was added to the "divider" field in this mutation.
func (m *InstrumentMutation) AddedDivider() (r int, exists bool) {
	v := m.adddivider
	if v == nil {
		return
	}
	return *v, true
}

// ClearDivider clears the value of the "divider" field.
func (m *InstrumentMutation) ClearDivider() {
	m.divider = nil
	m.adddivider = nil
	m.clearedFields[instrument.FieldDivider] = struct{}{}
}

// DividerCleared returns if the "divider" field was cleared in this mutation.
func (m *InstrumentMutation) DividerCleared() bool {
	_, ok := m.clearedFields[instrument.FieldDivider]
	return ok
}

// ResetDivider resets all changes to the "divider" field.
func (m *InstrumentMutation) ResetDivider() {
	m.divider = nil
	m.adddivider = nil
	delete(m.clearedFields, instrument.FieldDivider)
}

// SetStartDate sets the "start_date" field.
func (m *InstrumentMutation) SetStartDate(t time.Time) {
	m.start_date = &t
}

// StartDate returns the value of the "start_date" field in the mutation.
func (m *InstrumentMutation) StartDate() (r time.Time, exists bool) {
	v := m.start_date
	if v == nil {
		return
	}
	return *v, true
}

// OldStartDate returns the old "start_date" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldStartDate(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartDate: %w", err)
	}
	return oldValue.StartDate, nil
}

// ClearStartDate clears the value of the "start_date" field.
func (m *InstrumentMutation) ClearStartDate() {
	m.start_date = nil
	m.clearedFields[instrument.FieldStartDate] = struct{}{}
}

// StartDateCleared returns if the "start_date" field was cleared in this mutation.
func (m *InstrumentMutation) StartDateCleared() bool {
	_, ok := m.clearedFields[instrument.FieldStartDate]
	return ok
}

// ResetStartDate resets all changes to the "start_date" field.
func (m *InstrumentMutation) ResetStartDate() {
	m.start_date = nil
	delete(m.clearedFields, instrument.FieldStartDate)
}

// SetIsPause sets the "is_pause" field.
func (m *InstrumentMutation) SetIsPause(b bool) {
	m.is_pause = &b
}

// IsPause returns the value of the "is_pause" field in the mutation.
func (m *InstrumentMutation) IsPause() (r bool, exists bool) {
	v := m.is_pause
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPause returns the old "is_pause" field's value of the Instrument entity.
// If the Instrument object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstrumentMutation) OldIsPause(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPause is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPause requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPause: %w", err)
	}
	return oldValue.IsPause, nil
}

// ResetIsPause resets all changes to the "is_pause" field.
func (m *InstrumentMutation) ResetIsPause() {
	m.is_pause = nil
}

// AddStateIDs adds the "states" edge to the State entity by ids.
func (m *InstrumentMutation) AddStateIDs(ids ...uuid.UUID) {
	if m.states == nil {
		m.states = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.states[ids[i]] = struct{}{}
	}
}

// ClearStates clears the "states" edge to the State entity.
func (m *InstrumentMutation) ClearStates() {
	m.clearedstates = true
}

// StatesCleared reports if the "states" edge to the State entity was cleared.
func (m *InstrumentMutation) StatesCleared() bool {
	return m.clearedstates
}

// RemoveStateIDs removes the "states" edge to the State entity by IDs.
func (m *InstrumentMutation) RemoveStateIDs(ids ...uuid.UUID) {
	if m.removedstates == nil {
		m.removedstates = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.states, ids[i])
		m.removedstates[ids[i]] = struct{}{}
	}
}

// RemovedStates returns the removed IDs of the "states" edge to the State entity.
func (m *InstrumentMutation) RemovedStatesIDs() (ids []uuid.UUID) {
	for id := range m.removedstates {
		ids = append(ids, id)
	}
	return
}

// StatesIDs returns the "states" edge IDs in the mutation.
func (m *InstrumentMutation) StatesIDs() (ids []uuid.UUID) {
	for id := range m.states {
		ids = append(ids, id)
	}
	return
}

// ResetStates resets all changes to the "states" edge.
func (m *InstrumentMutation) ResetStates() {
	m.states = nil
	m.clearedstates = false
	m.removedstates = nil
}

// AddSyncTaskIDs adds the "sync_tasks" edge to the SyncTask entity by ids.
func (m *InstrumentMutation) AddSyncTaskIDs(ids ...uuid.UUID) {
	if m.sync_tasks == nil {
		m.sync_tasks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.sync_tasks[ids[i]] = struct{}{}
	}
}

// ClearSyncTasks clears the "sync_tasks" edge to the SyncTask entity.
func (m *InstrumentMutation) ClearSyncTasks() {
	m.clearedsync_tasks = true
}

// SyncTasksCleared reports if the "sync_tasks" edge to the SyncTask entity was cleared.
func (m *InstrumentMutation) SyncTasksCleared() bool {
	return m.clearedsync_tasks
}

// RemoveSyncTaskIDs removes the "sync_tasks" edge to the SyncTask entity by IDs.
func (m *InstrumentMutation) RemoveSyncTaskIDs(ids ...uuid.UUID) {
	if m.removedsync_tasks == nil {
		m.removedsync_tasks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.sync_tasks, ids[i])
		m.removedsync_tasks[ids[i]] = struct{}{}
	}
}

// RemovedSyncTasks returns the removed IDs of the "sync_tasks" edge to the SyncTask entity.
func (m *InstrumentMutation) RemovedSyncTasksIDs() (ids []uuid.UUID) {
	for id := range m.removedsync_tasks {
		ids = append(ids, id)
	}
	return
}

// SyncTasksIDs returns the "sync_tasks" edge IDs in the mutation.
func (m *InstrumentMutation) SyncTasksIDs() (ids []uuid.UUID) {
	for id := range m.sync_tasks {
		ids = append(ids, id)
	}
	return
}

// ResetSyncTasks resets all changes to the "sync_tasks" edge.
func (m *InstrumentMutation) ResetSyncTasks() {
	m.sync_tasks = nil
	m.clearedsync_tasks = false
	m.removedsync_tasks = nil
}

// Where appends a list predicates to the InstrumentMutation builder.
func (m *InstrumentMutation) Where(ps ...predicate.Instrument) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the InstrumentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *InstrumentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Instrument, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *InstrumentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *InstrumentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Instrument).
func (m *InstrumentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *InstrumentMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.name != nil {
		fields = append(fields, instrument.FieldName)
	}
	if m.description != nil {
		fields = append(fields, instrument.FieldDescription)
	}
	if m.asset_class != nil {
		fields = append(fields, instrument.FieldAssetClass)
	}
	if m.is_active != nil {
		fields = append(fields, instrument.FieldIsActive)
	}
	if m.divider != nil {
		fields = append(fields, instrument.FieldDivider)
	}
	if m.start_date != nil {
		fields = append(fields, instrument.FieldStartDate)
	}
	if m.is_pause != nil {
		fields = append(fields, instrument.FieldIsPause)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *InstrumentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case instrument.FieldName:
		return m.Name()
	case instrument.FieldDescription:
		return m.Description()
	case instrument.FieldAssetClass:
		return m.AssetClass()
	case instrument.FieldIsActive:
		return m.IsActive()
	case instrument.FieldDivider:
		return m.Divider()
	case instrument.FieldStartDate:
		return m.StartDate()
	case instrument.FieldIsPause:
		return m.IsPause()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *InstrumentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case instrument.FieldName:
		return m.OldName(ctx)
	case instrument.FieldDescription:
		return m.OldDescription(ctx)
	case instrument.FieldAssetClass:
		return m.OldAssetClass(ctx)
	case instrument.FieldIsActive:
		return m.OldIsActive(ctx)
	case instrument.FieldDivider:
		return m.OldDivider(ctx)
	case instrument.FieldStartDate:
		return m.OldStartDate(ctx)
	case instrument.FieldIsPause:
		return m.OldIsPause(ctx)
	}
	return nil, fmt.Errorf("unknown Instrument field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InstrumentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case instrument.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case instrument.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case instrument.FieldAssetClass:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAssetClass(v)
		return nil
	case instrument.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	case instrument.FieldDivider:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDivider(v)
		return nil
	case instrument.FieldStartDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartDate(v)
		return nil
	case instrument.FieldIsPause:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPause(v)
		return nil
	}
	return fmt.Errorf("unknown Instrument field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *InstrumentMutation) AddedFields() []string {
	var fields []string
	if m.adddivider != nil {
		fields = append(fields, instrument.FieldDivider)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *InstrumentMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case instrument.FieldDivider:
		return m.AddedDivider()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InstrumentMutation) AddField(name string, value ent.Value) error {
	switch name {
	case instrument.FieldDivider:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDivider(v)
		return nil
	}
	return fmt.Errorf("unknown Instrument numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *InstrumentMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(instrument.FieldDescription) {
		fields = append(fields, instrument.FieldDescription)
	}
	if m.FieldCleared(instrument.FieldAssetClass) {
		fields = append(fields, instrument.FieldAssetClass)
	}
	if m.FieldCleared(instrument.FieldDivider) {
		fields = append(fields, instrument.FieldDivider)
	}
	if m.FieldCleared(instrument.FieldStartDate) {
		fields = append(fields, instrument.FieldStartDate)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *InstrumentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *InstrumentMutation) ClearField(name string) error {
	switch name {
	case instrument.FieldDescription:
		m.ClearDescription()
		return nil
	case instrument.FieldAssetClass:
		m.ClearAssetClass()
		return nil
	case instrument.FieldDivider:
		m.ClearDivider()
		return nil
	case instrument.FieldStartDate:
		m.ClearStartDate()
		return nil
	}
	return fmt.Errorf("unknown Instrument nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *InstrumentMutation) ResetField(name string) error {
	switch name {
	case instrument.FieldName:
		m.ResetName()
		return nil
	case instrument.FieldDescription:
		m.ResetDescription()
		return nil
	case instrument.FieldAssetClass:
		m.ResetAssetClass()
		return nil
	case instrument.FieldIsActive:
		m.ResetIsActive()
		return nil
	case instrument.FieldDivider:
		m.ResetDivider()
		return nil
	case instrument.FieldStartDate:
		m.ResetStartDate()
		return nil
	case instrument.FieldIsPause:
		m.ResetIsPause()
		return nil
	}
	return fmt.Errorf("unknown Instrument field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *InstrumentMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.states != nil {
		edges = append(edges, instrument.EdgeStates)
	}
	if m.sync_tasks != nil {
		edges = append(edges, instrument.EdgeSyncTasks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *InstrumentMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case instrument.EdgeStates:
		ids := make([]ent.Value, 0, len(m.states))
		for id := range m.states {
			ids = append(ids, id)
		}
		return ids
	case instrument.EdgeSyncTasks:
		ids := make([]ent.Value, 0, len(m.sync_tasks))
		for id := range m.sync_tasks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *InstrumentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedstates != nil {
		edges = append(edges, instrument.EdgeStates)
	}
	if m.removedsync_tasks != nil {
		edges = append(edges, instrument.EdgeSyncTasks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *InstrumentMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case instrument.EdgeStates:
		ids := make([]ent.Value, 0, len(m.removedstates))
		for id := range m.removedstates {
			ids = append(ids, id)
		}
		return ids
	case instrument.EdgeSyncTasks:
		ids := make([]ent.Value, 0, len(m.removedsync_tasks))
		for id := range m.removedsync_tasks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *InstrumentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedstates {
		edges = append(edges, instrument.EdgeStates)
	}
	if m.clearedsync_tasks {
		edges = append(edges, instrument.EdgeSyncTasks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *InstrumentMutation) EdgeCleared(name string) bool {
	switch name {
	case instrument.EdgeStates:
		return m.clearedstates
	case instrument.EdgeSyncTasks:
		return m.clearedsync_tasks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *InstrumentMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Instrument unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *InstrumentMutation) ResetEdge(name string) error {
	switch name {
	case instrument.EdgeStates:
		m.ResetStates()
		return nil
	case instrument.EdgeSyncTasks:
		m.ResetSyncTasks()
		return nil
	}
	return fmt.Errorf("unknown Instrument edge %s", name)
}

// StateMutation represents an operation that mutates the State nodes in the graph.
type StateMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uuid.UUID
	job_type               *state.JobType
	timestamp              *time.Time
	status                 *state.Status
	previous_status        *state.PreviousStatus
	is_holiday             *bool
	resolved_tick_count    *int
	addresolved_tick_count *int
	retry_count            *int
	addretry_count         *int
	not_found_streak       *int
	addnot_found_streak    *int
	is_deleted             *bool
	updated_at             *time.Time
	clearedFields          map[string]struct{}
	instrument             *uuid.UUID
	clearedinstrument      bool
	done                   bool
	oldValue               func(context.Context) (*State, error)
	predicates             []predicate.State
}

var _ ent.Mutation = (*StateMutation)(nil)

// stateOption allows management of the mutation configuration using functional options.
type stateOption func(*StateMutation)

// newStateMutation creates new mutation for the State entity.
func newStateMutation(c config, op Op, opts ...stateOption) *StateMutation {
	m := &StateMutation{
		config:        c,
		op:            op,
		typ:           TypeState,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStateID sets the ID field of the mutation.
func withStateID(id uuid.UUID) stateOption {
	return func(m *StateMutation) {
		var (
			err   error
			once  sync.Once
			value *State
		)
		m.oldValue = func(ctx context.Context) (*State, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().State.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withState sets the old State of the mutation.
func withState(node *State) stateOption {
	return func(m *StateMutation) {
		m.oldValue = func(context.Context) (*State, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StateMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StateMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of State entities.
func (m *StateMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StateMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StateMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().State.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstrumentID sets the "instrument_id" field.
func (m *StateMutation) SetInstrumentID(u uuid.UUID) {
	m.instrument = &u
}

// InstrumentID returns the value of the "instrument_id" field in the mutation.
func (m *StateMutation) InstrumentID() (r uuid.UUID, exists bool) {
	v := m.instrument
	if v == nil {
		return
	}
	return *v, true
}

// OldInstrumentID returns the old "instrument_id" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldInstrumentID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstrumentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstrumentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstrumentID: %w", err)
	}
	return oldValue.InstrumentID, nil
}

// ResetInstrumentID resets all changes to the "instrument_id" field.
func (m *StateMutation) ResetInstrumentID() {
	m.instrument = nil
}

// SetJobType sets the "job_type" field.
func (m *StateMutation) SetJobType(st state.JobType) {
	m.job_type = &st
}

// JobType returns the value of the "job_type" field in the mutation.
func (m *StateMutation) JobType() (r state.JobType, exists bool) {
	v := m.job_type
	if v == nil {
		return
	}
	return *v, true
}

// OldJobType returns the old "job_type" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldJobType(ctx context.Context) (v state.JobType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobType: %w", err)
	}
	return oldValue.JobType, nil
}

// ResetJobType resets all changes to the "job_type" field.
func (m *StateMutation) ResetJobType() {
	m.job_type = nil
}

// SetTimestamp sets the "timestamp" field.
func (m *StateMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *StateMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *StateMutation) ResetTimestamp() {
	m.timestamp = nil
}

// SetStatus sets the "status" field.
func (m *StateMutation) SetStatus(s state.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *StateMutation) Status() (r state.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldStatus(ctx context.Context) (v state.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *StateMutation) ResetStatus() {
	m.status = nil
}

// SetPreviousStatus sets the "previous_status" field.
func (m *StateMutation) SetPreviousStatus(ss state.PreviousStatus) {
	m.previous_status = &ss
}

// PreviousStatus returns the value of the "previous_status" field in the mutation.
func (m *StateMutation) PreviousStatus() (r state.PreviousStatus, exists bool) {
	v := m.previous_status
	if v == nil {
		return
	}
	return *v, true
}

// OldPreviousStatus returns the old "previous_status" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldPreviousStatus(ctx context.Context) (v *state.PreviousStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPreviousStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPreviousStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPreviousStatus: %w", err)
	}
	return oldValue.PreviousStatus, nil
}

// ClearPreviousStatus clears the value of the "previous_status" field.
func (m *StateMutation) ClearPreviousStatus() {
	m.previous_status = nil
	m.clearedFields[state.FieldPreviousStatus] = struct{}{}
}

// PreviousStatusCleared returns if the "previous_status" field was cleared in this mutation.
func (m *StateMutation) PreviousStatusCleared() bool {
	_, ok := m.clearedFields[state.FieldPreviousStatus]
	return ok
}

// ResetPreviousStatus resets all changes to the "previous_status" field.
func (m *StateMutation) ResetPreviousStatus() {
	m.previous_status = nil
	delete(m.clearedFields, state.FieldPreviousStatus)
}

// SetIsHoliday sets the "is_holiday" field.
func (m *StateMutation) SetIsHoliday(b bool) {
	m.is_holiday = &b
}

// IsHoliday returns the value of the "is_holiday" field in the mutation.
func (m *StateMutation) IsHoliday() (r bool, exists bool) {
	v := m.is_holiday
	if v == nil {
		return
	}
	return *v, true
}

// OldIsHoliday returns the old "is_holiday" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldIsHoliday(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsHoliday is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsHoliday requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsHoliday: %w", err)
	}
	return oldValue.IsHoliday, nil
}

// ResetIsHoliday resets all changes to the "is_holiday" field.
func (m *StateMutation) ResetIsHoliday() {
	m.is_holiday = nil
}

// SetResolvedTickCount sets the "resolved_tick_count" field.
func (m *StateMutation) SetResolvedTickCount(i int) {
	m.resolved_tick_count = &i
	m.addresolved_tick_count = nil
}

// ResolvedTickCount returns the value of the "resolved_tick_count" field in the mutation.
func (m *StateMutation) ResolvedTickCount() (r int, exists bool) {
	v := m.resolved_tick_count
	if v == nil {
		return
	}
	return *v, true
}

// OldResolvedTickCount returns the old "resolved_tick_count" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldResolvedTickCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResolvedTickCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResolvedTickCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResolvedTickCount: %w", err)
	}
	return oldValue.ResolvedTickCount, nil
}

// AddResolvedTickCount adds i to the "resolved_tick_count" field.
func (m *StateMutation) AddResolvedTickCount(i int) {
	if m.addresolved_tick_count != nil {
		*m.addresolved_tick_count += i
	} else {
		m.addresolved_tick_count = &i
	}
}

// AddedResolvedTickCount returns the value that was added to the "resolved_tick_count" field in this mutation.
func (m *StateMutation) AddedResolvedTickCount() (r int, exists bool) {
	v := m.addresolved_tick_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetResolvedTickCount resets all changes to the "resolved_tick_count" field.
func (m *StateMutation) ResetResolvedTickCount() {
	m.resolved_tick_count = nil
	m.addresolved_tick_count = nil
}

// SetRetryCount sets the "retry_count" field.
func (m *StateMutation) SetRetryCount(i int) {
	m.retry_count = &i
	m.addretry_count = nil
}

// RetryCount returns the value of the "retry_count" field in the mutation.
func (m *StateMutation) RetryCount() (r int, exists bool) {
	v := m.retry_count
	if v == nil {
		return
	}
	return *v, true
}

// OldRetryCount returns the old "retry_count" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldRetryCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRetryCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRetryCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRetryCount: %w", err)
	}
	return oldValue.RetryCount, nil
}

// AddRetryCount adds i to the "retry_count" field.
func (m *StateMutation) AddRetryCount(i int) {
	if m.addretry_count != nil {
		*m.addretry_count += i
	} else {
		m.addretry_count = &i
	}
}

// AddedRetryCount returns the value that was added to the "retry_count" field in this mutation.
func (m *StateMutation) AddedRetryCount() (r int, exists bool) {
	v := m.addretry_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetRetryCount resets all changes to the "retry_count" field.
func (m *StateMutation) ResetRetryCount() {
	m.retry_count = nil
	m.addretry_count = nil
}

// SetNotFoundStreak sets the "not_found_streak" field.
func (m *StateMutation) SetNotFoundStreak(i int) {
	m.not_found_streak = &i
	m.addnot_found_streak = nil
}

// NotFoundStreak returns the value of the "not_found_streak" field in the mutation.
func (m *StateMutation) NotFoundStreak() (r int, exists bool) {
	v := m.not_found_streak
	if v == nil {
		return
	}
	return *v, true
}

// OldNotFoundStreak returns the old "not_found_streak" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldNotFoundStreak(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotFoundStreak is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotFoundStreak requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotFoundStreak: %w", err)
	}
	return oldValue.NotFoundStreak, nil
}

// AddNotFoundStreak adds i to the "not_found_streak" field.
func (m *StateMutation) AddNotFoundStreak(i int) {
	if m.addnot_found_streak != nil {
		*m.addnot_found_streak += i
	} else {
		m.addnot_found_streak = &i
	}
}

// AddedNotFoundStreak returns the value that was added to the "not_found_streak" field in this mutation.
func (m *StateMutation) AddedNotFoundStreak() (r int, exists bool) {
	v := m.addnot_found_streak
	if v == nil {
		return
	}
	return *v, true
}

// ResetNotFoundStreak resets all changes to the "not_found_streak" field.
func (m *StateMutation) ResetNotFoundStreak() {
	m.not_found_streak = nil
	m.addnot_found_streak = nil
}

// SetIsDeleted sets the "is_deleted" field.
func (m *StateMutation) SetIsDeleted(b bool) {
	m.is_deleted = &b
}

// IsDeleted returns the value of the "is_deleted" field in the mutation.
func (m *StateMutation) IsDeleted() (r bool, exists bool) {
	v := m.is_deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDeleted returns the old "is_deleted" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldIsDeleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDeleted: %w", err)
	}
	return oldValue.IsDeleted, nil
}

// ResetIsDeleted resets all changes to the "is_deleted" field.
func (m *StateMutation) ResetIsDeleted() {
	m.is_deleted = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *StateMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *StateMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the State entity.
// If the State object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StateMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *StateMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (m *StateMutation) ClearInstrument() {
	m.clearedinstrument = true
	m.clearedFields[state.FieldInstrumentID] = struct{}{}
}

// InstrumentCleared reports if the "instrument" edge to the Instrument entity was cleared.
func (m *StateMutation) InstrumentCleared() bool {
	return m.clearedinstrument
}

// InstrumentIDs returns the "instrument" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// InstrumentID instead. It exists only for internal usage by the builders.
func (m *StateMutation) InstrumentIDs() (ids []uuid.UUID) {
	if id := m.instrument; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetInstrument resets all changes to the "instrument" edge.
func (m *StateMutation) ResetInstrument() {
	m.instrument = nil
	m.clearedinstrument = false
}

// Where appends a list predicates to the StateMutation builder.
func (m *StateMutation) Where(ps ...predicate.State) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StateMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StateMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.State, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StateMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StateMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (State).
func (m *StateMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StateMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.instrument != nil {
		fields = append(fields, state.FieldInstrumentID)
	}
	if m.job_type != nil {
		fields = append(fields, state.FieldJobType)
	}
	if m.timestamp != nil {
		fields = append(fields, state.FieldTimestamp)
	}
	if m.status != nil {
		fields = append(fields, state.FieldStatus)
	}
	if m.previous_status != nil {
		fields = append(fields, state.FieldPreviousStatus)
	}
	if m.is_holiday != nil {
		fields = append(fields, state.FieldIsHoliday)
	}
	if m.resolved_tick_count != nil {
		fields = append(fields, state.FieldResolvedTickCount)
	}
	if m.retry_count != nil {
		fields = append(fields, state.FieldRetryCount)
	}
	if m.not_found_streak != nil {
		fields = append(fields, state.FieldNotFoundStreak)
	}
	if m.is_deleted != nil {
		fields = append(fields, state.FieldIsDeleted)
	}
	if m.updated_at != nil {
		fields = append(fields, state.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StateMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case state.FieldInstrumentID:
		return m.InstrumentID()
	case state.FieldJobType:
		return m.JobType()
	case state.FieldTimestamp:
		return m.Timestamp()
	case state.FieldStatus:
		return m.Status()
	case state.FieldPreviousStatus:
		return m.PreviousStatus()
	case state.FieldIsHoliday:
		return m.IsHoliday()
	case state.FieldResolvedTickCount:
		return m.ResolvedTickCount()
	case state.FieldRetryCount:
		return m.RetryCount()
	case state.FieldNotFoundStreak:
		return m.NotFoundStreak()
	case state.FieldIsDeleted:
		return m.IsDeleted()
	case state.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StateMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case state.FieldInstrumentID:
		return m.OldInstrumentID(ctx)
	case state.FieldJobType:
		return m.OldJobType(ctx)
	case state.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case state.FieldStatus:
		return m.OldStatus(ctx)
	case state.FieldPreviousStatus:
		return m.OldPreviousStatus(ctx)
	case state.FieldIsHoliday:
		return m.OldIsHoliday(ctx)
	case state.FieldResolvedTickCount:
		return m.OldResolvedTickCount(ctx)
	case state.FieldRetryCount:
		return m.OldRetryCount(ctx)
	case state.FieldNotFoundStreak:
		return m.OldNotFoundStreak(ctx)
	case state.FieldIsDeleted:
		return m.OldIsDeleted(ctx)
	case state.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown State field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StateMutation) SetField(name string, value ent.Value) error {
	switch name {
	case state.FieldInstrumentID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstrumentID(v)
		return nil
	case state.FieldJobType:
		v, ok := value.(state.JobType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobType(v)
		return nil
	case state.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case state.FieldStatus:
		v, ok := value.(state.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case state.FieldPreviousStatus:
		v, ok := value.(state.PreviousStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPreviousStatus(v)
		return nil
	case state.FieldIsHoliday:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsHoliday(v)
		return nil
	case state.FieldResolvedTickCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResolvedTickCount(v)
		return nil
	case state.FieldRetryCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRetryCount(v)
		return nil
	case state.FieldNotFoundStreak:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotFoundStreak(v)
		return nil
	case state.FieldIsDeleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDeleted(v)
		return nil
	case state.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown State field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StateMutation) AddedFields() []string {
	var fields []string
	if m.addresolved_tick_count != nil {
		fields = append(fields, state.FieldResolvedTickCount)
	}
	if m.addretry_count != nil {
		fields = append(fields, state.FieldRetryCount)
	}
	if m.addnot_found_streak != nil {
		fields = append(fields, state.FieldNotFoundStreak)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StateMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case state.FieldResolvedTickCount:
		return m.AddedResolvedTickCount()
	case state.FieldRetryCount:
		return m.AddedRetryCount()
	case state.FieldNotFoundStreak:
		return m.AddedNotFoundStreak()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StateMutation) AddField(name string, value ent.Value) error {
	switch name {
	case state.FieldResolvedTickCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddResolvedTickCount(v)
		return nil
	case state.FieldRetryCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRetryCount(v)
		return nil
	case state.FieldNotFoundStreak:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNotFoundStreak(v)
		return nil
	}
	return fmt.Errorf("unknown State numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StateMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(state.FieldPreviousStatus) {
		fields = append(fields, state.FieldPreviousStatus)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StateMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StateMutation) ClearField(name string) error {
	switch name {
	case state.FieldPreviousStatus:
		m.ClearPreviousStatus()
		return nil
	}
	return fmt.Errorf("unknown State nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StateMutation) ResetField(name string) error {
	switch name {
	case state.FieldInstrumentID:
		m.ResetInstrumentID()
		return nil
	case state.FieldJobType:
		m.ResetJobType()
		return nil
	case state.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case state.FieldStatus:
		m.ResetStatus()
		return nil
	case state.FieldPreviousStatus:
		m.ResetPreviousStatus()
		return nil
	case state.FieldIsHoliday:
		m.ResetIsHoliday()
		return nil
	case state.FieldResolvedTickCount:
		m.ResetResolvedTickCount()
		return nil
	case state.FieldRetryCount:
		m.ResetRetryCount()
		return nil
	case state.FieldNotFoundStreak:
		m.ResetNotFoundStreak()
		return nil
	case state.FieldIsDeleted:
		m.ResetIsDeleted()
		return nil
	case state.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown State field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StateMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.instrument != nil {
		edges = append(edges, state.EdgeInstrument)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StateMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case state.EdgeInstrument:
		if id := m.instrument; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StateMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StateMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StateMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedinstrument {
		edges = append(edges, state.EdgeInstrument)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StateMutation) EdgeCleared(name string) bool {
	switch name {
	case state.EdgeInstrument:
		return m.clearedinstrument
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StateMutation) ClearEdge(name string) error {
	switch name {
	case state.EdgeInstrument:
		m.ClearInstrument()
		return nil
	}
	return fmt.Errorf("unknown State unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StateMutation) ResetEdge(name string) error {
	switch name {
	case state.EdgeInstrument:
		m.ResetInstrument()
		return nil
	}
	return fmt.Errorf("unknown State edge %s", name)
}

// SyncTaskMutation represents an operation that mutates the SyncTask nodes in the graph.
type SyncTaskMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	target_date       *time.Time
	status            *synctask.Status
	created_at        *time.Time
	clearedFields     map[string]struct{}
	instrument        *uuid.UUID
	clearedinstrument bool
	done              bool
	oldValue          func(context.Context) (*SyncTask, error)
	predicates        []predicate.SyncTask
}

var _ ent.Mutation = (*SyncTaskMutation)(nil)

// synctaskOption allows management of the mutation configuration using functional options.
type synctaskOption func(*SyncTaskMutation)

// newSyncTaskMutation creates new mutation for the SyncTask entity.
func newSyncTaskMutation(c config, op Op, opts ...synctaskOption) *SyncTaskMutation {
	m := &SyncTaskMutation{
		config:        c,
		op:            op,
		typ:           TypeSyncTask,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSyncTaskID sets the ID field of the mutation.
func withSyncTaskID(id uuid.UUID) synctaskOption {
	return func(m *SyncTaskMutation) {
		var (
			err   error
			once  sync.Once
			value *SyncTask
		)
		m.oldValue = func(ctx context.Context) (*SyncTask, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SyncTask.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSyncTask sets the old SyncTask of the mutation.
func withSyncTask(node *SyncTask) synctaskOption {
	return func(m *SyncTaskMutation) {
		m.oldValue = func(context.Context) (*SyncTask, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SyncTaskMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SyncTaskMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SyncTask entities.
func (m *SyncTaskMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SyncTaskMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SyncTaskMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SyncTask.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInstrumentID sets the "instrument_id" field.
func (m *SyncTaskMutation) SetInstrumentID(u uuid.UUID) {
	m.instrument = &u
}

// InstrumentID returns the value of the "instrument_id" field in the mutation.
func (m *SyncTaskMutation) InstrumentID() (r uuid.UUID, exists bool) {
	v := m.instrument
	if v == nil {
		return
	}
	return *v, true
}

// OldInstrumentID returns the old "instrument_id" field's value of the SyncTask entity.
// If the SyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SyncTaskMutation) OldInstrumentID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInstrumentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInstrumentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInstrumentID: %w", err)
	}
	return oldValue.InstrumentID, nil
}

// ResetInstrumentID resets all changes to the "instrument_id" field.
func (m *SyncTaskMutation) ResetInstrumentID() {
	m.instrument = nil
}

// SetTargetDate sets the "target_date" field.
func (m *SyncTaskMutation) SetTargetDate(t time.Time) {
	m.target_date = &t
}

// TargetDate returns the value of the "target_date" field in the mutation.
func (m *SyncTaskMutation) TargetDate() (r time.Time, exists bool) {
	v := m.target_date
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetDate returns the old "target_date" field's value of the SyncTask entity.
// If the SyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SyncTaskMutation) OldTargetDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetDate: %w", err)
	}
	return oldValue.TargetDate, nil
}

// ResetTargetDate resets all changes to the "target_date" field.
func (m *SyncTaskMutation) ResetTargetDate() {
	m.target_date = nil
}

// SetStatus sets the "status" field.
func (m *SyncTaskMutation) SetStatus(s synctask.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SyncTaskMutation) Status() (r synctask.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the SyncTask entity.
// If the SyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SyncTaskMutation) OldStatus(ctx context.Context) (v synctask.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SyncTaskMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *SyncTaskMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SyncTaskMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SyncTask entity.
// If the SyncTask object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SyncTaskMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SyncTaskMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (m *SyncTaskMutation) ClearInstrument() {
	m.clearedinstrument = true
	m.clearedFields[synctask.FieldInstrumentID] = struct{}{}
}

// InstrumentCleared reports if the "instrument" edge to the Instrument entity was cleared.
func (m *SyncTaskMutation) InstrumentCleared() bool {
	return m.clearedinstrument
}

// InstrumentIDs returns the "instrument" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// InstrumentID instead. It exists only for internal usage by the builders.
func (m *SyncTaskMutation) InstrumentIDs() (ids []uuid.UUID) {
	if id := m.instrument; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetInstrument resets all changes to the "instrument" edge.
func (m *SyncTaskMutation) ResetInstrument() {
	m.instrument = nil
	m.clearedinstrument = false
}

// Where appends a list predicates to the SyncTaskMutation builder.
func (m *SyncTaskMutation) Where(ps ...predicate.SyncTask) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SyncTaskMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SyncTaskMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SyncTask, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SyncTaskMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SyncTaskMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SyncTask).
func (m *SyncTaskMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SyncTaskMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.instrument != nil {
		fields = append(fields, synctask.FieldInstrumentID)
	}
	if m.target_date != nil {
		fields = append(fields, synctask.FieldTargetDate)
	}
	if m.status != nil {
		fields = append(fields, synctask.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, synctask.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SyncTaskMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case synctask.FieldInstrumentID:
		return m.InstrumentID()
	case synctask.FieldTargetDate:
		return m.TargetDate()
	case synctask.FieldStatus:
		return m.Status()
	case synctask.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SyncTaskMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case synctask.FieldInstrumentID:
		return m.OldInstrumentID(ctx)
	case synctask.FieldTargetDate:
		return m.OldTargetDate(ctx)
	case synctask.FieldStatus:
		return m.OldStatus(ctx)
	case synctask.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown SyncTask field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SyncTaskMutation) SetField(name string, value ent.Value) error {
	switch name {
	case synctask.FieldInstrumentID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInstrumentID(v)
		return nil
	case synctask.FieldTargetDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetDate(v)
		return nil
	case synctask.FieldStatus:
		v, ok := value.(synctask.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case synctask.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown SyncTask field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SyncTaskMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SyncTaskMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SyncTaskMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SyncTask numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SyncTaskMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SyncTaskMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SyncTaskMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SyncTask nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SyncTaskMutation) ResetField(name string) error {
	switch name {
	case synctask.FieldInstrumentID:
		m.ResetInstrumentID()
		return nil
	case synctask.FieldTargetDate:
		m.ResetTargetDate()
		return nil
	case synctask.FieldStatus:
		m.ResetStatus()
		return nil
	case synctask.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown SyncTask field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SyncTaskMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.instrument != nil {
		edges = append(edges, synctask.EdgeInstrument)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SyncTaskMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case synctask.EdgeInstrument:
		if id := m.instrument; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SyncTaskMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SyncTaskMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SyncTaskMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedinstrument {
		edges = append(edges, synctask.EdgeInstrument)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SyncTaskMutation) EdgeCleared(name string) bool {
	switch name {
	case synctask.EdgeInstrument:
		return m.clearedinstrument
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SyncTaskMutation) ClearEdge(name string) error {
	switch name {
	case synctask.EdgeInstrument:
		m.ClearInstrument()
		return nil
	}
	return fmt.Errorf("unknown SyncTask unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SyncTaskMutation) ResetEdge(name string) error {
	switch name {
	case synctask.EdgeInstrument:
		m.ResetInstrument()
		return nil
	}
	return fmt.Errorf("unknown SyncTask edge %s", name)
}

// TimeframeMutation represents an operation that mutates the Timeframe nodes in the graph.
type TimeframeMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	name          *string
	minutes       *int
	addminutes    *int
	is_active     *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Timeframe, error)
	predicates    []predicate.Timeframe
}

var _ ent.Mutation = (*TimeframeMutation)(nil)

// timeframeOption allows management of the mutation configuration using functional options.
type timeframeOption func(*TimeframeMutation)

// newTimeframeMutation creates new mutation for the Timeframe entity.
func newTimeframeMutation(c config, op Op, opts ...timeframeOption) *TimeframeMutation {
	m := &TimeframeMutation{
		config:        c,
		op:            op,
		typ:           TypeTimeframe,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTimeframeID sets the ID field of the mutation.
func withTimeframeID(id uuid.UUID) timeframeOption {
	return func(m *TimeframeMutation) {
		var (
			err   error
			once  sync.Once
			value *Timeframe
		)
		m.oldValue = func(ctx context.Context) (*Timeframe, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Timeframe.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTimeframe sets the old Timeframe of the mutation.
func withTimeframe(node *Timeframe) timeframeOption {
	return func(m *TimeframeMutation) {
		m.oldValue = func(context.Context) (*Timeframe, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TimeframeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TimeframeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Timeframe entities.
func (m *TimeframeMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TimeframeMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TimeframeMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Timeframe.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *TimeframeMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TimeframeMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Timeframe entity.
// If the Timeframe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TimeframeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TimeframeMutation) ResetName() {
	m.name = nil
}

// SetMinutes sets the "minutes" field.
func (m *TimeframeMutation) SetMinutes(i int) {
	m.minutes = &i
	m.addminutes = nil
}

// Minutes returns the value of the "minutes" field in the mutation.
func (m *TimeframeMutation) Minutes() (r int, exists bool) {
	v := m.minutes
	if v == nil {
		return
	}
	return *v, true
}

// OldMinutes returns the old "minutes" field's value of the Timeframe entity.
// If the Timeframe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TimeframeMutation) OldMinutes(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMinutes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMinutes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMinutes: %w", err)
	}
	return oldValue.Minutes, nil
}

// AddMinutes adds i to the "minutes" field.
func (m *TimeframeMutation) AddMinutes(i int) {
	if m.addminutes != nil {
		*m.addminutes += i
	} else {
		m.addminutes = &i
	}
}

// AddedMinutes returns the value that was added to the "minutes" field in this mutation.
func (m *TimeframeMutation) AddedMinutes() (r int, exists bool) {
	v := m.addminutes
	if v == nil {
		return
	}
	return *v, true
}

// ResetMinutes resets all changes to the "minutes" field.
func (m *TimeframeMutation) ResetMinutes() {
	m.minutes = nil
	m.addminutes = nil
}

// SetIsActive sets the "is_active" field.
func (m *TimeframeMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *TimeframeMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the Timeframe entity.
// If the Timeframe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TimeframeMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *TimeframeMutation) ResetIsActive() {
	m.is_active = nil
}

// Where appends a list predicates to the TimeframeMutation builder.
func (m *TimeframeMutation) Where(ps ...predicate.Timeframe) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TimeframeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TimeframeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Timeframe, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TimeframeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TimeframeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Timeframe).
func (m *TimeframeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TimeframeMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, timeframe.FieldName)
	}
	if m.minutes != nil {
		fields = append(fields, timeframe.FieldMinutes)
	}
	if m.is_active != nil {
		fields = append(fields, timeframe.FieldIsActive)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TimeframeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case timeframe.FieldName:
		return m.Name()
	case timeframe.FieldMinutes:
		return m.Minutes()
	case timeframe.FieldIsActive:
		return m.IsActive()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TimeframeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case timeframe.FieldName:
		return m.OldName(ctx)
	case timeframe.FieldMinutes:
		return m.OldMinutes(ctx)
	case timeframe.FieldIsActive:
		return m.OldIsActive(ctx)
	}
	return nil, fmt.Errorf("unknown Timeframe field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TimeframeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case timeframe.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case timeframe.FieldMinutes:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMinutes(v)
		return nil
	case timeframe.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	}
	return fmt.Errorf("unknown Timeframe field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TimeframeMutation) AddedFields() []string {
	var fields []string
	if m.addminutes != nil {
		fields = append(fields, timeframe.FieldMinutes)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TimeframeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case timeframe.FieldMinutes:
		return m.AddedMinutes()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TimeframeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case timeframe.FieldMinutes:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMinutes(v)
		return nil
	}
	return fmt.Errorf("unknown Timeframe numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TimeframeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TimeframeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TimeframeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Timeframe nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TimeframeMutation) ResetField(name string) error {
	switch name {
	case timeframe.FieldName:
		m.ResetName()
		return nil
	case timeframe.FieldMinutes:
		m.ResetMinutes()
		return nil
	case timeframe.FieldIsActive:
		m.ResetIsActive()
		return nil
	}
	return fmt.Errorf("unknown Timeframe field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TimeframeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TimeframeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TimeframeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TimeframeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TimeframeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TimeframeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TimeframeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Timeframe unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TimeframeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Timeframe edge %s", name)
}
