// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
)

// StateUpdate is the builder for updating State entities.
type StateUpdate struct {
	config
	hooks    []Hook
	mutation *StateMutation
}

// Where appends a list predicates to the StateUpdate builder.
func (_u *StateUpdate) Where(ps ...predicate.State) *StateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstrumentID sets the "instrument_id" field.
func (_u *StateUpdate) SetInstrumentID(v uuid.UUID) *StateUpdate {
	_u.mutation.SetInstrumentID(v)
	return _u
}

// SetNillableInstrumentID sets the "instrument_id" field if the given value is not nil.
func (_u *StateUpdate) SetNillableInstrumentID(v *uuid.UUID) *StateUpdate {
	if v != nil {
		_u.SetInstrumentID(*v)
	}
	return _u
}

// SetJobType sets the "job_type" field.
func (_u *StateUpdate) SetJobType(v state.JobType) *StateUpdate {
	_u.mutation.SetJobType(v)
	return _u
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (_u *StateUpdate) SetNillableJobType(v *state.JobType) *StateUpdate {
	if v != nil {
		_u.SetJobType(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *StateUpdate) SetTimestamp(v time.Time) *StateUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *StateUpdate) SetNillableTimestamp(v *time.Time) *StateUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StateUpdate) SetStatus(v state.Status) *StateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StateUpdate) SetNillableStatus(v *state.Status) *StateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPreviousStatus sets the "previous_status" field.
func (_u *StateUpdate) SetPreviousStatus(v state.PreviousStatus) *StateUpdate {
	_u.mutation.SetPreviousStatus(v)
	return _u
}

// SetNillablePreviousStatus sets the "previous_status" field if the given value is not nil.
func (_u *StateUpdate) SetNillablePreviousStatus(v *state.PreviousStatus) *StateUpdate {
	if v != nil {
		_u.SetPreviousStatus(*v)
	}
	return _u
}

// ClearPreviousStatus clears the value of the "previous_status" field.
func (_u *StateUpdate) ClearPreviousStatus() *StateUpdate {
	_u.mutation.ClearPreviousStatus()
	return _u
}

// SetIsHoliday sets the "is_holiday" field.
func (_u *StateUpdate) SetIsHoliday(v bool) *StateUpdate {
	_u.mutation.SetIsHoliday(v)
	return _u
}

// SetNillableIsHoliday sets the "is_holiday" field if the given value is not nil.
func (_u *StateUpdate) SetNillableIsHoliday(v *bool) *StateUpdate {
	if v != nil {
		_u.SetIsHoliday(*v)
	}
	return _u
}

// SetResolvedTickCount sets the "resolved_tick_count" field.
func (_u *StateUpdate) SetResolvedTickCount(v int) *StateUpdate {
	_u.mutation.ResetResolvedTickCount()
	_u.mutation.SetResolvedTickCount(v)
	return _u
}

// SetNillableResolvedTickCount sets the "resolved_tick_count" field if the given value is not nil.
func (_u *StateUpdate) SetNillableResolvedTickCount(v *int) *StateUpdate {
	if v != nil {
		_u.SetResolvedTickCount(*v)
	}
	return _u
}

// AddResolvedTickCount adds value to the "resolved_tick_count" field.
func (_u *StateUpdate) AddResolvedTickCount(v int) *StateUpdate {
	_u.mutation.AddResolvedTickCount(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *StateUpdate) SetRetryCount(v int) *StateUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *StateUpdate) SetNillableRetryCount(v *int) *StateUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *StateUpdate) AddRetryCount(v int) *StateUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNotFoundStreak sets the "not_found_streak" field.
func (_u *StateUpdate) SetNotFoundStreak(v int) *StateUpdate {
	_u.mutation.ResetNotFoundStreak()
	_u.mutation.SetNotFoundStreak(v)
	return _u
}

// SetNillableNotFoundStreak sets the "not_found_streak" field if the given value is not nil.
func (_u *StateUpdate) SetNillableNotFoundStreak(v *int) *StateUpdate {
	if v != nil {
		_u.SetNotFoundStreak(*v)
	}
	return _u
}

// AddNotFoundStreak adds value to the "not_found_streak" field.
func (_u *StateUpdate) AddNotFoundStreak(v int) *StateUpdate {
	_u.mutation.AddNotFoundStreak(v)
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *StateUpdate) SetIsDeleted(v bool) *StateUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *StateUpdate) SetNillableIsDeleted(v *bool) *StateUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StateUpdate) SetUpdatedAt(v time.Time) *StateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StateUpdate) SetNillableUpdatedAt(v *time.Time) *StateUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_u *StateUpdate) SetInstrument(v *Instrument) *StateUpdate {
	return _u.SetInstrumentID(v.ID)
}

// Mutation returns the StateMutation object of the builder.
func (_u *StateUpdate) Mutation() *StateMutation {
	return _u.mutation
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (_u *StateUpdate) ClearInstrument() *StateUpdate {
	_u.mutation.ClearInstrument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateUpdate) check() error {
	if v, ok := _u.mutation.JobType(); ok {
		if err := state.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "State.job_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := state.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "State.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousStatus(); ok {
		if err := state.PreviousStatusValidator(v); err != nil {
			return &ValidationError{Name: "previous_status", err: fmt.Errorf(`ent: validator failed for field "State.previous_status": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "State.instrument"`)
	}
	return nil
}

func (_u *StateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(state.Table, state.Columns, sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobType(); ok {
		_spec.SetField(state.FieldJobType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(state.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(state.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PreviousStatus(); ok {
		_spec.SetField(state.FieldPreviousStatus, field.TypeEnum, value)
	}
	if _u.mutation.PreviousStatusCleared() {
		_spec.ClearField(state.FieldPreviousStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.IsHoliday(); ok {
		_spec.SetField(state.FieldIsHoliday, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResolvedTickCount(); ok {
		_spec.SetField(state.FieldResolvedTickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResolvedTickCount(); ok {
		_spec.AddField(state.FieldResolvedTickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(state.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(state.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotFoundStreak(); ok {
		_spec.SetField(state.FieldNotFoundStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotFoundStreak(); ok {
		_spec.AddField(state.FieldNotFoundStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(state.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(state.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstrumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   state.InstrumentTable,
			Columns: []string{state.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   state.InstrumentTable,
			Columns: []string{state.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.State
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{state.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StateUpdateOne is the builder for updating a single State entity.
type StateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StateMutation
}

// SetInstrumentID sets the "instrument_id" field.
func (_u *StateUpdateOne) SetInstrumentID(v uuid.UUID) *StateUpdateOne {
	_u.mutation.SetInstrumentID(v)
	return _u
}

// SetNillableInstrumentID sets the "instrument_id" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableInstrumentID(v *uuid.UUID) *StateUpdateOne {
	if v != nil {
		_u.SetInstrumentID(*v)
	}
	return _u
}

// SetJobType sets the "job_type" field.
func (_u *StateUpdateOne) SetJobType(v state.JobType) *StateUpdateOne {
	_u.mutation.SetJobType(v)
	return _u
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableJobType(v *state.JobType) *StateUpdateOne {
	if v != nil {
		_u.SetJobType(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *StateUpdateOne) SetTimestamp(v time.Time) *StateUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableTimestamp(v *time.Time) *StateUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StateUpdateOne) SetStatus(v state.Status) *StateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableStatus(v *state.Status) *StateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPreviousStatus sets the "previous_status" field.
func (_u *StateUpdateOne) SetPreviousStatus(v state.PreviousStatus) *StateUpdateOne {
	_u.mutation.SetPreviousStatus(v)
	return _u
}

// SetNillablePreviousStatus sets the "previous_status" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillablePreviousStatus(v *state.PreviousStatus) *StateUpdateOne {
	if v != nil {
		_u.SetPreviousStatus(*v)
	}
	return _u
}

// ClearPreviousStatus clears the value of the "previous_status" field.
func (_u *StateUpdateOne) ClearPreviousStatus() *StateUpdateOne {
	_u.mutation.ClearPreviousStatus()
	return _u
}

// SetIsHoliday sets the "is_holiday" field.
func (_u *StateUpdateOne) SetIsHoliday(v bool) *StateUpdateOne {
	_u.mutation.SetIsHoliday(v)
	return _u
}

// SetNillableIsHoliday sets the "is_holiday" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableIsHoliday(v *bool) *StateUpdateOne {
	if v != nil {
		_u.SetIsHoliday(*v)
	}
	return _u
}

// SetResolvedTickCount sets the "resolved_tick_count" field.
func (_u *StateUpdateOne) SetResolvedTickCount(v int) *StateUpdateOne {
	_u.mutation.ResetResolvedTickCount()
	_u.mutation.SetResolvedTickCount(v)
	return _u
}

// SetNillableResolvedTickCount sets the "resolved_tick_count" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableResolvedTickCount(v *int) *StateUpdateOne {
	if v != nil {
		_u.SetResolvedTickCount(*v)
	}
	return _u
}

// AddResolvedTickCount adds value to the "resolved_tick_count" field.
func (_u *StateUpdateOne) AddResolvedTickCount(v int) *StateUpdateOne {
	_u.mutation.AddResolvedTickCount(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *StateUpdateOne) SetRetryCount(v int) *StateUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableRetryCount(v *int) *StateUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *StateUpdateOne) AddRetryCount(v int) *StateUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNotFoundStreak sets the "not_found_streak" field.
func (_u *StateUpdateOne) SetNotFoundStreak(v int) *StateUpdateOne {
	_u.mutation.ResetNotFoundStreak()
	_u.mutation.SetNotFoundStreak(v)
	return _u
}

// SetNillableNotFoundStreak sets the "not_found_streak" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableNotFoundStreak(v *int) *StateUpdateOne {
	if v != nil {
		_u.SetNotFoundStreak(*v)
	}
	return _u
}

// AddNotFoundStreak adds value to the "not_found_streak" field.
func (_u *StateUpdateOne) AddNotFoundStreak(v int) *StateUpdateOne {
	_u.mutation.AddNotFoundStreak(v)
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *StateUpdateOne) SetIsDeleted(v bool) *StateUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableIsDeleted(v *bool) *StateUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StateUpdateOne) SetUpdatedAt(v time.Time) *StateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableUpdatedAt(v *time.Time) *StateUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_u *StateUpdateOne) SetInstrument(v *Instrument) *StateUpdateOne {
	return _u.SetInstrumentID(v.ID)
}

// Mutation returns the StateMutation object of the builder.
func (_u *StateUpdateOne) Mutation() *StateMutation {
	return _u.mutation
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (_u *StateUpdateOne) ClearInstrument() *StateUpdateOne {
	_u.mutation.ClearInstrument()
	return _u
}

// Where appends a list predicates to the StateUpdate builder.
func (_u *StateUpdateOne) Where(ps ...predicate.State) *StateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StateUpdateOne) Select(field string, fields ...string) *StateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated State entity.
func (_u *StateUpdateOne) Save(ctx context.Context) (*State, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateUpdateOne) SaveX(ctx context.Context) *State {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateUpdateOne) check() error {
	if v, ok := _u.mutation.JobType(); ok {
		if err := state.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "State.job_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := state.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "State.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousStatus(); ok {
		if err := state.PreviousStatusValidator(v); err != nil {
			return &ValidationError{Name: "previous_status", err: fmt.Errorf(`ent: validator failed for field "State.previous_status": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "State.instrument"`)
	}
	return nil
}

func (_u *StateUpdateOne) sqlSave(ctx context.Context) (_node *State, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(state.Table, state.Columns, sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "State.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, state.FieldID)
		for _, f := range fields {
			if !state.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != state.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobType(); ok {
		_spec.SetField(state.FieldJobType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(state.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(state.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PreviousStatus(); ok {
		_spec.SetField(state.FieldPreviousStatus, field.TypeEnum, value)
	}
	if _u.mutation.PreviousStatusCleared() {
		_spec.ClearField(state.FieldPreviousStatus, field.TypeEnum)
	}
	if value, ok := _u.mutation.IsHoliday(); ok {
		_spec.SetField(state.FieldIsHoliday, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResolvedTickCount(); ok {
		_spec.SetField(state.FieldResolvedTickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResolvedTickCount(); ok {
		_spec.AddField(state.FieldResolvedTickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(state.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(state.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NotFoundStreak(); ok {
		_spec.SetField(state.FieldNotFoundStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNotFoundStreak(); ok {
		_spec.AddField(state.FieldNotFoundStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(state.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(state.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstrumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   state.InstrumentTable,
			Columns: []string{state.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   state.InstrumentTable,
			Columns: []string{state.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.State
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &State{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{state.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
