// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
)

// State is the model entity for the State schema.
type State struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InstrumentID holds the value of the "instrument_id" field.
	InstrumentID uuid.UUID `json:"instrument_id,omitempty"`
	// JobType holds the value of the "job_type" field.
	JobType state.JobType `json:"job_type,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Status holds the value of the "status" field.
	Status state.Status `json:"status,omitempty"`
	// PreviousStatus holds the value of the "previous_status" field.
	PreviousStatus *state.PreviousStatus `json:"previous_status,omitempty"`
	// IsHoliday holds the value of the "is_holiday" field.
	IsHoliday bool `json:"is_holiday,omitempty"`
	// ResolvedTickCount holds the value of the "resolved_tick_count" field.
	ResolvedTickCount int `json:"resolved_tick_count,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// NotFoundStreak holds the value of the "not_found_streak" field.
	NotFoundStreak int `json:"not_found_streak,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StateQuery when eager-loading is set.
	Edges        StateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StateEdges holds the relations/edges for other nodes in the graph.
type StateEdges struct {
	// Instrument holds the value of the instrument edge.
	Instrument *Instrument `json:"instrument,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InstrumentOrErr returns the Instrument value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StateEdges) InstrumentOrErr() (*Instrument, error) {
	if e.Instrument != nil {
		return e.Instrument, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: instrument.Label}
	}
	return nil, &NotLoadedError{edge: "instrument"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*State) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case state.FieldIsHoliday, state.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case state.FieldResolvedTickCount, state.FieldRetryCount, state.FieldNotFoundStreak:
			values[i] = new(sql.NullInt64)
		case state.FieldJobType, state.FieldStatus, state.FieldPreviousStatus:
			values[i] = new(sql.NullString)
		case state.FieldTimestamp, state.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case state.FieldID, state.FieldInstrumentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the State fields.
func (_m *State) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case state.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case state.FieldInstrumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field instrument_id", values[i])
			} else if value != nil {
				_m.InstrumentID = *value
			}
		case state.FieldJobType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_type", values[i])
			} else if value.Valid {
				_m.JobType = state.JobType(value.String)
			}
		case state.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case state.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = state.Status(value.String)
			}
		case state.FieldPreviousStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field previous_status", values[i])
			} else if value.Valid {
				_m.PreviousStatus = new(state.PreviousStatus)
				*_m.PreviousStatus = state.PreviousStatus(value.String)
			}
		case state.FieldIsHoliday:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_holiday", values[i])
			} else if value.Valid {
				_m.IsHoliday = value.Bool
			}
		case state.FieldResolvedTickCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_tick_count", values[i])
			} else if value.Valid {
				_m.ResolvedTickCount = int(value.Int64)
			}
		case state.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case state.FieldNotFoundStreak:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field not_found_streak", values[i])
			} else if value.Valid {
				_m.NotFoundStreak = int(value.Int64)
			}
		case state.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		case state.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the State.
// This includes values selected through modifiers, order, etc.
func (_m *State) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstrument queries the "instrument" edge of the State entity.
func (_m *State) QueryInstrument() *InstrumentQuery {
	return NewStateClient(_m.config).QueryInstrument(_m)
}

// Update returns a builder for updating this State.
// Note that you need to call State.Unwrap() before calling this method if this State
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *State) Update() *StateUpdateOne {
	return NewStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the State entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *State) Unwrap() *State {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: State is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *State) String() string {
	var builder strings.Builder
	builder.WriteString("State(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("instrument_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstrumentID))
	builder.WriteString(", ")
	builder.WriteString("job_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobType))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.PreviousStatus; v != nil {
		builder.WriteString("previous_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_holiday=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsHoliday))
	builder.WriteString(", ")
	builder.WriteString("resolved_tick_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResolvedTickCount))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("not_found_streak=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotFoundStreak))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// States is a parsable slice of State.
type States []*State
