// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/state"
)

// StateCreate is the builder for creating a State entity.
type StateCreate struct {
	config
	mutation *StateMutation
	hooks    []Hook
}

// SetInstrumentID sets the "instrument_id" field.
func (_c *StateCreate) SetInstrumentID(v uuid.UUID) *StateCreate {
	_c.mutation.SetInstrumentID(v)
	return _c
}

// SetJobType sets the "job_type" field.
func (_c *StateCreate) SetJobType(v state.JobType) *StateCreate {
	_c.mutation.SetJobType(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *StateCreate) SetTimestamp(v time.Time) *StateCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StateCreate) SetStatus(v state.Status) *StateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetPreviousStatus sets the "previous_status" field.
func (_c *StateCreate) SetPreviousStatus(v state.PreviousStatus) *StateCreate {
	_c.mutation.SetPreviousStatus(v)
	return _c
}

// SetNillablePreviousStatus sets the "previous_status" field if the given value is not nil.
func (_c *StateCreate) SetNillablePreviousStatus(v *state.PreviousStatus) *StateCreate {
	if v != nil {
		_c.SetPreviousStatus(*v)
	}
	return _c
}

// SetIsHoliday sets the "is_holiday" field.
func (_c *StateCreate) SetIsHoliday(v bool) *StateCreate {
	_c.mutation.SetIsHoliday(v)
	return _c
}

// SetNillableIsHoliday sets the "is_holiday" field if the given value is not nil.
func (_c *StateCreate) SetNillableIsHoliday(v *bool) *StateCreate {
	if v != nil {
		_c.SetIsHoliday(*v)
	}
	return _c
}

// SetResolvedTickCount sets the "resolved_tick_count" field.
func (_c *StateCreate) SetResolvedTickCount(v int) *StateCreate {
	_c.mutation.SetResolvedTickCount(v)
	return _c
}

// SetNillableResolvedTickCount sets the "resolved_tick_count" field if the given value is not nil.
func (_c *StateCreate) SetNillableResolvedTickCount(v *int) *StateCreate {
	if v != nil {
		_c.SetResolvedTickCount(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *StateCreate) SetRetryCount(v int) *StateCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *StateCreate) SetNillableRetryCount(v *int) *StateCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetNotFoundStreak sets the "not_found_streak" field.
func (_c *StateCreate) SetNotFoundStreak(v int) *StateCreate {
	_c.mutation.SetNotFoundStreak(v)
	return _c
}

// SetNillableNotFoundStreak sets the "not_found_streak" field if the given value is not nil.
func (_c *StateCreate) SetNillableNotFoundStreak(v *int) *StateCreate {
	if v != nil {
		_c.SetNotFoundStreak(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *StateCreate) SetIsDeleted(v bool) *StateCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *StateCreate) SetNillableIsDeleted(v *bool) *StateCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StateCreate) SetUpdatedAt(v time.Time) *StateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *StateCreate) SetTraceID(v string) *StateCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *StateCreate) SetNillableTraceID(v *string) *StateCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StateCreate) SetID(v uuid.UUID) *StateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StateCreate) SetNillableID(v *uuid.UUID) *StateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_c *StateCreate) SetInstrument(v *Instrument) *StateCreate {
	return _c.SetInstrumentID(v.ID)
}

// Mutation returns the StateMutation object of the builder.
func (_c *StateCreate) Mutation() *StateMutation {
	return _c.mutation
}

// Save creates the State in the database.
func (_c *StateCreate) Save(ctx context.Context) (*State, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StateCreate) SaveX(ctx context.Context) *State {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StateCreate) defaults() error {
	if _, ok := _c.mutation.IsHoliday(); !ok {
		v := state.DefaultIsHoliday
		_c.mutation.SetIsHoliday(v)
	}
	if _, ok := _c.mutation.ResolvedTickCount(); !ok {
		v := state.DefaultResolvedTickCount
		_c.mutation.SetResolvedTickCount(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := state.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.NotFoundStreak(); !ok {
		v := state.DefaultNotFoundStreak
		_c.mutation.SetNotFoundStreak(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := state.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if state.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized state.DefaultID (forgotten import ent/runtime?)")
		}
		v := state.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *StateCreate) check() error {
	if _, ok := _c.mutation.InstrumentID(); !ok {
		return &ValidationError{Name: "instrument_id", err: errors.New(`ent: missing required field "State.instrument_id"`)}
	}
	if _, ok := _c.mutation.JobType(); !ok {
		return &ValidationError{Name: "job_type", err: errors.New(`ent: missing required field "State.job_type"`)}
	}
	if v, ok := _c.mutation.JobType(); ok {
		if err := state.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "State.job_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "State.timestamp"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "State.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := state.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "State.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PreviousStatus(); ok {
		if err := state.PreviousStatusValidator(v); err != nil {
			return &ValidationError{Name: "previous_status", err: fmt.Errorf(`ent: validator failed for field "State.previous_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsHoliday(); !ok {
		return &ValidationError{Name: "is_holiday", err: errors.New(`ent: missing required field "State.is_holiday"`)}
	}
	if _, ok := _c.mutation.ResolvedTickCount(); !ok {
		return &ValidationError{Name: "resolved_tick_count", err: errors.New(`ent: missing required field "State.resolved_tick_count"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "State.retry_count"`)}
	}
	if _, ok := _c.mutation.NotFoundStreak(); !ok {
		return &ValidationError{Name: "not_found_streak", err: errors.New(`ent: missing required field "State.not_found_streak"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "State.is_deleted"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "State.updated_at"`)}
	}
	if len(_c.mutation.InstrumentIDs()) == 0 {
		return &ValidationError{Name: "instrument", err: errors.New(`ent: missing required edge "State.instrument"`)}
	}
	return nil
}

func (_c *StateCreate) sqlSave(ctx context.Context) (*State, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StateCreate) createSpec() (*State, *sqlgraph.CreateSpec) {
	var (
		_node = &State{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(state.Table, sqlgraph.NewFieldSpec(state.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.State
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.JobType(); ok {
		_spec.SetField(state.FieldJobType, field.TypeEnum, value)
		_node.JobType = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(state.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(state.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PreviousStatus(); ok {
		_spec.SetField(state.FieldPreviousStatus, field.TypeEnum, value)
		_node.PreviousStatus = &value
	}
	if value, ok := _c.mutation.IsHoliday(); ok {
		_spec.SetField(state.FieldIsHoliday, field.TypeBool, value)
		_node.IsHoliday = value
	}
	if value, ok := _c.mutation.ResolvedTickCount(); ok {
		_spec.SetField(state.FieldResolvedTickCount, field.TypeInt, value)
		_node.ResolvedTickCount = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(state.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.NotFoundStreak(); ok {
		_spec.SetField(state.FieldNotFoundStreak, field.TypeInt, value)
		_node.NotFoundStreak = value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(state.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(state.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(state.FieldTraceID, field.TypeString, value)
		_node.TraceID = &value
	}
	if nodes := _c.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   state.InstrumentTable,
			Columns: []string{state.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.State
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InstrumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StateCreateBulk is the builder for creating many State entities in bulk.
type StateCreateBulk struct {
	config
	err      error
	builders []*StateCreate
}

// Save creates the State entities in the database.
func (_c *StateCreateBulk) Save(ctx context.Context) ([]*State, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*State, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StateCreateBulk) SaveX(ctx context.Context) []*State {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
