// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
)

// SyncTaskCreate is the builder for creating a SyncTask entity.
type SyncTaskCreate struct {
	config
	mutation *SyncTaskMutation
	hooks    []Hook
}

// SetInstrumentID sets the "instrument_id" field.
func (_c *SyncTaskCreate) SetInstrumentID(v uuid.UUID) *SyncTaskCreate {
	_c.mutation.SetInstrumentID(v)
	return _c
}

// SetTargetDate sets the "target_date" field.
func (_c *SyncTaskCreate) SetTargetDate(v time.Time) *SyncTaskCreate {
	_c.mutation.SetTargetDate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SyncTaskCreate) SetStatus(v synctask.Status) *SyncTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SyncTaskCreate) SetNillableStatus(v *synctask.Status) *SyncTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHoursCount sets the "hours_count" field.
func (_c *SyncTaskCreate) SetHoursCount(v int) *SyncTaskCreate {
	_c.mutation.SetHoursCount(v)
	return _c
}

// SetNillableHoursCount sets the "hours_count" field if the given value is not nil.
func (_c *SyncTaskCreate) SetNillableHoursCount(v *int) *SyncTaskCreate {
	if v != nil {
		_c.SetHoursCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncTaskCreate) SetCreatedAt(v time.Time) *SyncTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncTaskCreate) SetNillableCreatedAt(v *time.Time) *SyncTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SyncTaskCreate) SetID(v uuid.UUID) *SyncTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SyncTaskCreate) SetNillableID(v *uuid.UUID) *SyncTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_c *SyncTaskCreate) SetInstrument(v *Instrument) *SyncTaskCreate {
	return _c.SetInstrumentID(v.ID)
}

// Mutation returns the SyncTaskMutation object of the builder.
func (_c *SyncTaskCreate) Mutation() *SyncTaskMutation {
	return _c.mutation
}

// Save creates the SyncTask in the database.
func (_c *SyncTaskCreate) Save(ctx context.Context) (*SyncTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncTaskCreate) SaveX(ctx context.Context) *SyncTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncTaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := synctask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.HoursCount(); !ok {
		v := synctask.DefaultHoursCount
		_c.mutation.SetHoursCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := synctask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := synctask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncTaskCreate) check() error {
	if _, ok := _c.mutation.InstrumentID(); !ok {
		return &ValidationError{Name: "instrument_id", err: errors.New(`ent: missing required field "SyncTask.instrument_id"`)}
	}
	if _, ok := _c.mutation.TargetDate(); !ok {
		return &ValidationError{Name: "target_date", err: errors.New(`ent: missing required field "SyncTask.target_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SyncTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := synctask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HoursCount(); !ok {
		return &ValidationError{Name: "hours_count", err: errors.New(`ent: missing required field "SyncTask.hours_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncTask.created_at"`)}
	}
	if len(_c.mutation.InstrumentIDs()) == 0 {
		return &ValidationError{Name: "instrument", err: errors.New(`ent: missing required edge "SyncTask.instrument"`)}
	}
	return nil
}

func (_c *SyncTaskCreate) sqlSave(ctx context.Context) (*SyncTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncTaskCreate) createSpec() (*SyncTask, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(synctask.Table, sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.SyncTask
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TargetDate(); ok {
		_spec.SetField(synctask.FieldTargetDate, field.TypeTime, value)
		_node.TargetDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(synctask.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HoursCount(); ok {
		_spec.SetField(synctask.FieldHoursCount, field.TypeInt, value)
		_node.HoursCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(synctask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   synctask.InstrumentTable,
			Columns: []string{synctask.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InstrumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SyncTaskCreateBulk is the builder for creating many SyncTask entities in bulk.
type SyncTaskCreateBulk struct {
	config
	err      error
	builders []*SyncTaskCreate
}

// Save creates the SyncTask entities in the database.
func (_c *SyncTaskCreateBulk) Save(ctx context.Context) ([]*SyncTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncTaskCreateBulk) SaveX(ctx context.Context) []*SyncTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
