// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
)

// SyncTaskUpdate is the builder for updating SyncTask entities.
type SyncTaskUpdate struct {
	config
	hooks    []Hook
	mutation *SyncTaskMutation
}

// Where appends a list predicates to the SyncTaskUpdate builder.
func (_u *SyncTaskUpdate) Where(ps ...predicate.SyncTask) *SyncTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstrumentID sets the "instrument_id" field.
func (_u *SyncTaskUpdate) SetInstrumentID(v uuid.UUID) *SyncTaskUpdate {
	_u.mutation.SetInstrumentID(v)
	return _u
}

// SetNillableInstrumentID sets the "instrument_id" field if the given value is not nil.
func (_u *SyncTaskUpdate) SetNillableInstrumentID(v *uuid.UUID) *SyncTaskUpdate {
	if v != nil {
		_u.SetInstrumentID(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *SyncTaskUpdate) SetTargetDate(v time.Time) *SyncTaskUpdate {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *SyncTaskUpdate) SetNillableTargetDate(v *time.Time) *SyncTaskUpdate {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncTaskUpdate) SetStatus(v synctask.Status) *SyncTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncTaskUpdate) SetNillableStatus(v *synctask.Status) *SyncTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_u *SyncTaskUpdate) SetInstrument(v *Instrument) *SyncTaskUpdate {
	return _u.SetInstrumentID(v.ID)
}

// Mutation returns the SyncTaskMutation object of the builder.
func (_u *SyncTaskUpdate) Mutation() *SyncTaskMutation {
	return _u.mutation
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (_u *SyncTaskUpdate) ClearInstrument() *SyncTaskUpdate {
	_u.mutation.ClearInstrument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := synctask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncTask.status": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncTask.instrument"`)
	}
	return nil
}

func (_u *SyncTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(synctask.Table, synctask.Columns, sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(synctask.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(synctask.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.InstrumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   synctask.InstrumentTable,
			Columns: []string{synctask.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   synctask.InstrumentTable,
			Columns: []string{synctask.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.SyncTask
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synctask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncTaskUpdateOne is the builder for updating a single SyncTask entity.
type SyncTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncTaskMutation
}

// SetInstrumentID sets the "instrument_id" field.
func (_u *SyncTaskUpdateOne) SetInstrumentID(v uuid.UUID) *SyncTaskUpdateOne {
	_u.mutation.SetInstrumentID(v)
	return _u
}

// SetNillableInstrumentID sets the "instrument_id" field if the given value is not nil.
func (_u *SyncTaskUpdateOne) SetNillableInstrumentID(v *uuid.UUID) *SyncTaskUpdateOne {
	if v != nil {
		_u.SetInstrumentID(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *SyncTaskUpdateOne) SetTargetDate(v time.Time) *SyncTaskUpdateOne {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *SyncTaskUpdateOne) SetNillableTargetDate(v *time.Time) *SyncTaskUpdateOne {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncTaskUpdateOne) SetStatus(v synctask.Status) *SyncTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncTaskUpdateOne) SetNillableStatus(v *synctask.Status) *SyncTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInstrument sets the "instrument" edge to the Instrument entity.
func (_u *SyncTaskUpdateOne) SetInstrument(v *Instrument) *SyncTaskUpdateOne {
	return _u.SetInstrumentID(v.ID)
}

// Mutation returns the SyncTaskMutation object of the builder.
func (_u *SyncTaskUpdateOne) Mutation() *SyncTaskMutation {
	return _u.mutation
}

// ClearInstrument clears the "instrument" edge to the Instrument entity.
func (_u *SyncTaskUpdateOne) ClearInstrument() *SyncTaskUpdateOne {
	_u.mutation.ClearInstrument()
	return _u
}

// Where appends a list predicates to the SyncTaskUpdate builder.
func (_u *SyncTaskUpdateOne) Where(ps ...predicate.SyncTask) *SyncTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncTaskUpdateOne) Select(field string, fields ...string) *SyncTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncTask entity.
func (_u *SyncTaskUpdateOne) Save(ctx context.Context) (*SyncTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncTaskUpdateOne) SaveX(ctx context.Context) *SyncTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := synctask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncTask.status": %w`, err)}
		}
	}
	if _u.mutation.InstrumentCleared() && len(_u.mutation.InstrumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncTask.instrument"`)
	}
	return nil
}

func (_u *SyncTaskUpdateOne) sqlSave(ctx context.Context) (_node *SyncTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(synctask.Table, synctask.Columns, sqlgraph.NewFieldSpec(synctask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, synctask.FieldID)
		for _, f := range fields {
			if !synctask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != synctask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(synctask.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(synctask.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.InstrumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   synctask.InstrumentTable,
			Columns: []string{synctask.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstrumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   synctask.InstrumentTable,
			Columns: []string{synctask.InstrumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instrument.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.SyncTask
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.SyncTask
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &SyncTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{synctask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
