// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/instrument"
	"github.com/sanjari-dev/geonera-ingestion/ent/synctask"
)

// SyncTask is the model entity for the SyncTask schema.
type SyncTask struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InstrumentID holds the value of the "instrument_id" field.
	InstrumentID uuid.UUID `json:"instrument_id,omitempty"`
	// TargetDate holds the value of the "target_date" field.
	TargetDate time.Time `json:"target_date,omitempty"`
	// Status holds the value of the "status" field.
	Status synctask.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SyncTaskQuery when eager-loading is set.
	Edges        SyncTaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SyncTaskEdges holds the relations/edges for other nodes in the graph.
type SyncTaskEdges struct {
	// Instrument holds the value of the instrument edge.
	Instrument *Instrument `json:"instrument,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InstrumentOrErr returns the Instrument value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SyncTaskEdges) InstrumentOrErr() (*Instrument, error) {
	if e.Instrument != nil {
		return e.Instrument, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: instrument.Label}
	}
	return nil, &NotLoadedError{edge: "instrument"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case synctask.FieldStatus:
			values[i] = new(sql.NullString)
		case synctask.FieldTargetDate, synctask.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case synctask.FieldID, synctask.FieldInstrumentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncTask fields.
func (_m *SyncTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case synctask.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case synctask.FieldInstrumentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field instrument_id", values[i])
			} else if value != nil {
				_m.InstrumentID = *value
			}
		case synctask.FieldTargetDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field target_date", values[i])
			} else if value.Valid {
				_m.TargetDate = value.Time
			}
		case synctask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = synctask.Status(value.String)
			}
		case synctask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncTask.
// This includes values selected through modifiers, order, etc.
func (_m *SyncTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInstrument queries the "instrument" edge of the SyncTask entity.
func (_m *SyncTask) QueryInstrument() *InstrumentQuery {
	return NewSyncTaskClient(_m.config).QueryInstrument(_m)
}

// Update returns a builder for updating this SyncTask.
// Note that you need to call SyncTask.Unwrap() before calling this method if this SyncTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SyncTask) Update() *SyncTaskUpdateOne {
	return NewSyncTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SyncTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SyncTask) Unwrap() *SyncTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SyncTask) String() string {
	var builder strings.Builder
	builder.WriteString("SyncTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("instrument_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstrumentID))
	builder.WriteString(", ")
	builder.WriteString("target_date=")
	builder.WriteString(_m.TargetDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SyncTasks is a parsable slice of SyncTask.
type SyncTasks []*SyncTask
