// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
	"github.com/sanjari-dev/geonera-ingestion/ent/timeframe"
)

// TimeframeUpdate is the builder for updating Timeframe entities.
type TimeframeUpdate struct {
	config
	hooks    []Hook
	mutation *TimeframeMutation
}

// Where appends a list predicates to the TimeframeUpdate builder.
func (_u *TimeframeUpdate) Where(ps ...predicate.Timeframe) *TimeframeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TimeframeUpdate) SetName(v string) *TimeframeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TimeframeUpdate) SetNillableName(v *string) *TimeframeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMinutes sets the "minutes" field.
func (_u *TimeframeUpdate) SetMinutes(v int) *TimeframeUpdate {
	_u.mutation.ResetMinutes()
	_u.mutation.SetMinutes(v)
	return _u
}

// SetNillableMinutes sets the "minutes" field if the given value is not nil.
func (_u *TimeframeUpdate) SetNillableMinutes(v *int) *TimeframeUpdate {
	if v != nil {
		_u.SetMinutes(*v)
	}
	return _u
}

// AddMinutes adds value to the "minutes" field.
func (_u *TimeframeUpdate) AddMinutes(v int) *TimeframeUpdate {
	_u.mutation.AddMinutes(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TimeframeUpdate) SetIsActive(v bool) *TimeframeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TimeframeUpdate) SetNillableIsActive(v *bool) *TimeframeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the TimeframeMutation object of the builder.
func (_u *TimeframeUpdate) Mutation() *TimeframeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimeframeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimeframeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimeframeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimeframeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimeframeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := timeframe.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timeframe.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Minutes(); ok {
		if err := timeframe.MinutesValidator(v); err != nil {
			return &ValidationError{Name: "minutes", err: fmt.Errorf(`ent: validator failed for field "Timeframe.minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *TimeframeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timeframe.Table, timeframe.Columns, sqlgraph.NewFieldSpec(timeframe.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(timeframe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Minutes(); ok {
		_spec.SetField(timeframe.FieldMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinutes(); ok {
		_spec.AddField(timeframe.FieldMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(timeframe.FieldIsActive, field.TypeBool, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Timeframe
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timeframe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimeframeUpdateOne is the builder for updating a single Timeframe entity.
type TimeframeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TimeframeMutation
}

// SetName sets the "name" field.
func (_u *TimeframeUpdateOne) SetName(v string) *TimeframeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TimeframeUpdateOne) SetNillableName(v *string) *TimeframeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMinutes sets the "minutes" field.
func (_u *TimeframeUpdateOne) SetMinutes(v int) *TimeframeUpdateOne {
	_u.mutation.ResetMinutes()
	_u.mutation.SetMinutes(v)
	return _u
}

// SetNillableMinutes sets the "minutes" field if the given value is not nil.
func (_u *TimeframeUpdateOne) SetNillableMinutes(v *int) *TimeframeUpdateOne {
	if v != nil {
		_u.SetMinutes(*v)
	}
	return _u
}

// AddMinutes adds value to the "minutes" field.
func (_u *TimeframeUpdateOne) AddMinutes(v int) *TimeframeUpdateOne {
	_u.mutation.AddMinutes(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TimeframeUpdateOne) SetIsActive(v bool) *TimeframeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TimeframeUpdateOne) SetNillableIsActive(v *bool) *TimeframeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// Mutation returns the TimeframeMutation object of the builder.
func (_u *TimeframeUpdateOne) Mutation() *TimeframeMutation {
	return _u.mutation
}

// Where appends a list predicates to the TimeframeUpdate builder.
func (_u *TimeframeUpdateOne) Where(ps ...predicate.Timeframe) *TimeframeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimeframeUpdateOne) Select(field string, fields ...string) *TimeframeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Timeframe entity.
func (_u *TimeframeUpdateOne) Save(ctx context.Context) (*Timeframe, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimeframeUpdateOne) SaveX(ctx context.Context) *Timeframe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimeframeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimeframeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimeframeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := timeframe.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timeframe.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Minutes(); ok {
		if err := timeframe.MinutesValidator(v); err != nil {
			return &ValidationError{Name: "minutes", err: fmt.Errorf(`ent: validator failed for field "Timeframe.minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *TimeframeUpdateOne) sqlSave(ctx context.Context) (_node *Timeframe, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timeframe.Table, timeframe.Columns, sqlgraph.NewFieldSpec(timeframe.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Timeframe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timeframe.FieldID)
		for _, f := range fields {
			if !timeframe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timeframe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(timeframe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Minutes(); ok {
		_spec.SetField(timeframe.FieldMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinutes(); ok {
		_spec.AddField(timeframe.FieldMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(timeframe.FieldIsActive, field.TypeBool, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Timeframe
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Timeframe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timeframe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
