// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/timeframe"
)

// TimeframeCreate is the builder for creating a Timeframe entity.
type TimeframeCreate struct {
	config
	mutation *TimeframeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TimeframeCreate) SetName(v string) *TimeframeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetMinutes sets the "minutes" field.
func (_c *TimeframeCreate) SetMinutes(v int) *TimeframeCreate {
	_c.mutation.SetMinutes(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TimeframeCreate) SetIsActive(v bool) *TimeframeCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TimeframeCreate) SetNillableIsActive(v *bool) *TimeframeCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TimeframeCreate) SetID(v uuid.UUID) *TimeframeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TimeframeCreate) SetNillableID(v *uuid.UUID) *TimeframeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TimeframeMutation object of the builder.
func (_c *TimeframeCreate) Mutation() *TimeframeMutation {
	return _c.mutation
}

// Save creates the Timeframe in the database.
func (_c *TimeframeCreate) Save(ctx context.Context) (*Timeframe, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimeframeCreate) SaveX(ctx context.Context) *Timeframe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeframeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeframeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimeframeCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := timeframe.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := timeframe.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimeframeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Timeframe.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := timeframe.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timeframe.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Minutes(); !ok {
		return &ValidationError{Name: "minutes", err: errors.New(`ent: missing required field "Timeframe.minutes"`)}
	}
	if v, ok := _c.mutation.Minutes(); ok {
		if err := timeframe.MinutesValidator(v); err != nil {
			return &ValidationError{Name: "minutes", err: fmt.Errorf(`ent: validator failed for field "Timeframe.minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Timeframe.is_active"`)}
	}
	return nil
}

func (_c *TimeframeCreate) sqlSave(ctx context.Context) (*Timeframe, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimeframeCreate) createSpec() (*Timeframe, *sqlgraph.CreateSpec) {
	var (
		_node = &Timeframe{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timeframe.Table, sqlgraph.NewFieldSpec(timeframe.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Timeframe
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(timeframe.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Minutes(); ok {
		_spec.SetField(timeframe.FieldMinutes, field.TypeInt, value)
		_node.Minutes = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(timeframe.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	return _node, _spec
}

// TimeframeCreateBulk is the builder for creating many Timeframe entities in bulk.
type TimeframeCreateBulk struct {
	config
	err      error
	builders []*TimeframeCreate
}

// Save creates the Timeframe entities in the database.
func (_c *TimeframeCreateBulk) Save(ctx context.Context) ([]*Timeframe, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Timeframe, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimeframeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimeframeCreateBulk) SaveX(ctx context.Context) []*Timeframe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeframeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeframeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
