// Code generated by ent, DO NOT EDIT.

package state

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the state type in the database.
	Label = "state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstrumentID holds the string denoting the instrument_id field in the database.
	FieldInstrumentID = "instrument_id"
	// FieldJobType holds the string denoting the job_type field in the database.
	FieldJobType = "job_type"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPreviousStatus holds the string denoting the previous_status field in the database.
	FieldPreviousStatus = "previous_status"
	// FieldIsHoliday holds the string denoting the is_holiday field in the database.
	FieldIsHoliday = "is_holiday"
	// FieldResolvedTickCount holds the string denoting the resolved_tick_count field in the database.
	FieldResolvedTickCount = "resolved_tick_count"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNotFoundStreak holds the string denoting the not_found_streak field in the database.
	FieldNotFoundStreak = "not_found_streak"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// EdgeInstrument holds the string denoting the instrument edge name in mutations.
	EdgeInstrument = "instrument"
	// Table holds the table name of the state in the database.
	Table = "states"
	// InstrumentTable is the table that holds the instrument relation/edge.
	InstrumentTable = "states"
	// InstrumentInverseTable is the table name for the Instrument entity.
	// It exists in this package in order to avoid circular dependency with the "instrument" package.
	InstrumentInverseTable = "instruments"
	// InstrumentColumn is the table column denoting the instrument relation/edge.
	InstrumentColumn = "instrument_id"
)

// Columns holds all SQL columns for state fields.
var Columns = []string{
	FieldID,
	FieldInstrumentID,
	FieldJobType,
	FieldTimestamp,
	FieldStatus,
	FieldPreviousStatus,
	FieldIsHoliday,
	FieldResolvedTickCount,
	FieldRetryCount,
	FieldNotFoundStreak,
	FieldIsDeleted,
	FieldUpdatedAt,
	FieldTraceID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/sanjari-dev/geonera-ingestion/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultIsHoliday holds the default value on creation for the "is_holiday" field.
	DefaultIsHoliday bool
	// DefaultResolvedTickCount holds the default value on creation for the "resolved_tick_count" field.
	DefaultResolvedTickCount int
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultNotFoundStreak holds the default value on creation for the "not_found_streak" field.
	DefaultNotFoundStreak int
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// JobType defines the type for the "job_type" enum field.
type JobType string

// JobType values.
const (
	JobTypeTICK   JobType = "TICK"
	JobTypeCANDLE JobType = "CANDLE"
)

func (jt JobType) String() string {
	return string(jt)
}

// JobTypeValidator is a validator for the "job_type" field enum values. It is called by the builders before save.
func JobTypeValidator(jt JobType) error {
	switch jt {
	case JobTypeTICK, JobTypeCANDLE:
		return nil
	default:
		return fmt.Errorf("state: invalid enum value for job_type field: %q", jt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusPENDING   Status = "PENDING"
	StatusPROCESSED Status = "PROCESSED"
	StatusNOT_FOUND Status = "NOT_FOUND"
	StatusFAILED    Status = "FAILED"
	StatusCOMPLETED Status = "COMPLETED"
	StatusBROKEN    Status = "BROKEN"
	StatusCONFIRMED Status = "CONFIRMED"
	StatusABANDONED Status = "ABANDONED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusPROCESSED, StatusNOT_FOUND, StatusFAILED, StatusCOMPLETED, StatusBROKEN, StatusCONFIRMED, StatusABANDONED:
		return nil
	default:
		return fmt.Errorf("state: invalid enum value for status field: %q", s)
	}
}

// PreviousStatus defines the type for the "previous_status" enum field.
type PreviousStatus string

// PreviousStatus values.
const (
	PreviousStatusPENDING   PreviousStatus = "PENDING"
	PreviousStatusPROCESSED PreviousStatus = "PROCESSED"
	PreviousStatusNOT_FOUND PreviousStatus = "NOT_FOUND"
	PreviousStatusFAILED    PreviousStatus = "FAILED"
	PreviousStatusCOMPLETED PreviousStatus = "COMPLETED"
	PreviousStatusBROKEN    PreviousStatus = "BROKEN"
	PreviousStatusCONFIRMED PreviousStatus = "CONFIRMED"
	PreviousStatusABANDONED PreviousStatus = "ABANDONED"
)

func (ps PreviousStatus) String() string {
	return string(ps)
}

// PreviousStatusValidator is a validator for the "previous_status" field enum values. It is called by the builders before save.
func PreviousStatusValidator(ps PreviousStatus) error {
	switch ps {
	case PreviousStatusPENDING, PreviousStatusPROCESSED, PreviousStatusNOT_FOUND, PreviousStatusFAILED, PreviousStatusCOMPLETED, PreviousStatusBROKEN, PreviousStatusCONFIRMED, PreviousStatusABANDONED:
		return nil
	default:
		return fmt.Errorf("state: invalid enum value for previous_status field: %q", ps)
	}
}

// OrderOption defines the ordering options for the State queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstrumentID orders the results by the instrument_id field.
func ByInstrumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstrumentID, opts...).ToFunc()
}

// ByJobType orders the results by the job_type field.
func ByJobType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobType, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPreviousStatus orders the results by the previous_status field.
func ByPreviousStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousStatus, opts...).ToFunc()
}

// ByIsHoliday orders the results by the is_holiday field.
func ByIsHoliday(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHoliday, opts...).ToFunc()
}

// ByResolvedTickCount orders the results by the resolved_tick_count field.
func ByResolvedTickCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedTickCount, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNotFoundStreak orders the results by the not_found_streak field.
func ByNotFoundStreak(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotFoundStreak, opts...).ToFunc()
}

// ByIsDeleted orders the results by the is_deleted field.
func ByIsDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDeleted, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// ByInstrumentField orders the results by instrument field.
func ByInstrumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInstrumentStep(), sql.OrderByField(field, opts...))
	}
}
func newInstrumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InstrumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InstrumentTable, InstrumentColumn),
	)
}
