// Code generated by ent, DO NOT EDIT.

package state

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sanjari-dev/geonera-ingestion/ent/internal"
	"github.com/sanjari-dev/geonera-ingestion/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.State {
	return predicate.State(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.State {
	return predicate.State(sql.FieldLTE(FieldID, id))
}

// InstrumentID applies equality check predicate on the "instrument_id" field. It's identical to InstrumentIDEQ.
func InstrumentID(v uuid.UUID) predicate.State {
	return predicate.State(sql.FieldEQ(FieldInstrumentID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.State {
	return predicate.State(sql.FieldEQ(FieldTimestamp, v))
}

// IsHoliday applies equality check predicate on the "is_holiday" field. It's identical to IsHolidayEQ.
func IsHoliday(v bool) predicate.State {
	return predicate.State(sql.FieldEQ(FieldIsHoliday, v))
}

// ResolvedTickCount applies equality check predicate on the "resolved_tick_count" field. It's identical to ResolvedTickCountEQ.
func ResolvedTickCount(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldResolvedTickCount, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldRetryCount, v))
}

// NotFoundStreak applies equality check predicate on the "not_found_streak" field. It's identical to NotFoundStreakEQ.
func NotFoundStreak(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldNotFoundStreak, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.State {
	return predicate.State(sql.FieldEQ(FieldIsDeleted, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.State {
	return predicate.State(sql.FieldEQ(FieldUpdatedAt, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.State {
	return predicate.State(sql.FieldEQ(FieldTraceID, v))
}

// InstrumentIDEQ applies the EQ predicate on the "instrument_id" field.
func InstrumentIDEQ(v uuid.UUID) predicate.State {
	return predicate.State(sql.FieldEQ(FieldInstrumentID, v))
}

// InstrumentIDNEQ applies the NEQ predicate on the "instrument_id" field.
func InstrumentIDNEQ(v uuid.UUID) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldInstrumentID, v))
}

// InstrumentIDIn applies the In predicate on the "instrument_id" field.
func InstrumentIDIn(vs ...uuid.UUID) predicate.State {
	return predicate.State(sql.FieldIn(FieldInstrumentID, vs...))
}

// InstrumentIDNotIn applies the NotIn predicate on the "instrument_id" field.
func InstrumentIDNotIn(vs ...uuid.UUID) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldInstrumentID, vs...))
}

// JobTypeEQ applies the EQ predicate on the "job_type" field.
func JobTypeEQ(v JobType) predicate.State {
	return predicate.State(sql.FieldEQ(FieldJobType, v))
}

// JobTypeNEQ applies the NEQ predicate on the "job_type" field.
func JobTypeNEQ(v JobType) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldJobType, v))
}

// JobTypeIn applies the In predicate on the "job_type" field.
func JobTypeIn(vs ...JobType) predicate.State {
	return predicate.State(sql.FieldIn(FieldJobType, vs...))
}

// JobTypeNotIn applies the NotIn predicate on the "job_type" field.
func JobTypeNotIn(vs ...JobType) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldJobType, vs...))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.State {
	return predicate.State(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.State {
	return predicate.State(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.State {
	return predicate.State(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.State {
	return predicate.State(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.State {
	return predicate.State(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.State {
	return predicate.State(sql.FieldLTE(FieldTimestamp, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.State {
	return predicate.State(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.State {
	return predicate.State(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldStatus, vs...))
}

// PreviousStatusEQ applies the EQ predicate on the "previous_status" field.
func PreviousStatusEQ(v PreviousStatus) predicate.State {
	return predicate.State(sql.FieldEQ(FieldPreviousStatus, v))
}

// PreviousStatusNEQ applies the NEQ predicate on the "previous_status" field.
func PreviousStatusNEQ(v PreviousStatus) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldPreviousStatus, v))
}

// PreviousStatusIn applies the In predicate on the "previous_status" field.
func PreviousStatusIn(vs ...PreviousStatus) predicate.State {
	return predicate.State(sql.FieldIn(FieldPreviousStatus, vs...))
}

// PreviousStatusNotIn applies the NotIn predicate on the "previous_status" field.
func PreviousStatusNotIn(vs ...PreviousStatus) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldPreviousStatus, vs...))
}

// PreviousStatusIsNil applies the IsNil predicate on the "previous_status" field.
func PreviousStatusIsNil() predicate.State {
	return predicate.State(sql.FieldIsNull(FieldPreviousStatus))
}

// PreviousStatusNotNil applies the NotNil predicate on the "previous_status" field.
func PreviousStatusNotNil() predicate.State {
	return predicate.State(sql.FieldNotNull(FieldPreviousStatus))
}

// IsHolidayEQ applies the EQ predicate on the "is_holiday" field.
func IsHolidayEQ(v bool) predicate.State {
	return predicate.State(sql.FieldEQ(FieldIsHoliday, v))
}

// IsHolidayNEQ applies the NEQ predicate on the "is_holiday" field.
func IsHolidayNEQ(v bool) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldIsHoliday, v))
}

// ResolvedTickCountEQ applies the EQ predicate on the "resolved_tick_count" field.
func ResolvedTickCountEQ(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldResolvedTickCount, v))
}

// ResolvedTickCountNEQ applies the NEQ predicate on the "resolved_tick_count" field.
func ResolvedTickCountNEQ(v int) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldResolvedTickCount, v))
}

// ResolvedTickCountIn applies the In predicate on the "resolved_tick_count" field.
func ResolvedTickCountIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldIn(FieldResolvedTickCount, vs...))
}

// ResolvedTickCountNotIn applies the NotIn predicate on the "resolved_tick_count" field.
func ResolvedTickCountNotIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldResolvedTickCount, vs...))
}

// ResolvedTickCountGT applies the GT predicate on the "resolved_tick_count" field.
func ResolvedTickCountGT(v int) predicate.State {
	return predicate.State(sql.FieldGT(FieldResolvedTickCount, v))
}

// ResolvedTickCountGTE applies the GTE predicate on the "resolved_tick_count" field.
func ResolvedTickCountGTE(v int) predicate.State {
	return predicate.State(sql.FieldGTE(FieldResolvedTickCount, v))
}

// ResolvedTickCountLT applies the LT predicate on the "resolved_tick_count" field.
func ResolvedTickCountLT(v int) predicate.State {
	return predicate.State(sql.FieldLT(FieldResolvedTickCount, v))
}

// ResolvedTickCountLTE applies the LTE predicate on the "resolved_tick_count" field.
func ResolvedTickCountLTE(v int) predicate.State {
	return predicate.State(sql.FieldLTE(FieldResolvedTickCount, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.State {
	return predicate.State(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.State {
	return predicate.State(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.State {
	return predicate.State(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.State {
	return predicate.State(sql.FieldLTE(FieldRetryCount, v))
}

// NotFoundStreakEQ applies the EQ predicate on the "not_found_streak" field.
func NotFoundStreakEQ(v int) predicate.State {
	return predicate.State(sql.FieldEQ(FieldNotFoundStreak, v))
}

// NotFoundStreakNEQ applies the NEQ predicate on the "not_found_streak" field.
func NotFoundStreakNEQ(v int) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldNotFoundStreak, v))
}

// NotFoundStreakIn applies the In predicate on the "not_found_streak" field.
func NotFoundStreakIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldIn(FieldNotFoundStreak, vs...))
}

// NotFoundStreakNotIn applies the NotIn predicate on the "not_found_streak" field.
func NotFoundStreakNotIn(vs ...int) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldNotFoundStreak, vs...))
}

// NotFoundStreakGT applies the GT predicate on the "not_found_streak" field.
func NotFoundStreakGT(v int) predicate.State {
	return predicate.State(sql.FieldGT(FieldNotFoundStreak, v))
}

// NotFoundStreakGTE applies the GTE predicate on the "not_found_streak" field.
func NotFoundStreakGTE(v int) predicate.State {
	return predicate.State(sql.FieldGTE(FieldNotFoundStreak, v))
}

// NotFoundStreakLT applies the LT predicate on the "not_found_streak" field.
func NotFoundStreakLT(v int) predicate.State {
	return predicate.State(sql.FieldLT(FieldNotFoundStreak, v))
}

// NotFoundStreakLTE applies the LTE predicate on the "not_found_streak" field.
func NotFoundStreakLTE(v int) predicate.State {
	return predicate.State(sql.FieldLTE(FieldNotFoundStreak, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.State {
	return predicate.State(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldIsDeleted, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.State {
	return predicate.State(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.State {
	return predicate.State(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.State {
	return predicate.State(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.State {
	return predicate.State(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.State {
	return predicate.State(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.State {
	return predicate.State(sql.FieldLTE(FieldUpdatedAt, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.State {
	return predicate.State(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.State {
	return predicate.State(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.State {
	return predicate.State(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.State {
	return predicate.State(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.State {
	return predicate.State(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.State {
	return predicate.State(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.State {
	return predicate.State(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.State {
	return predicate.State(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.State {
	return predicate.State(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.State {
	return predicate.State(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.State {
	return predicate.State(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDIsNil applies the IsNil predicate on the "trace_id" field.
func TraceIDIsNil() predicate.State {
	return predicate.State(sql.FieldIsNull(FieldTraceID))
}

// TraceIDNotNil applies the NotNil predicate on the "trace_id" field.
func TraceIDNotNil() predicate.State {
	return predicate.State(sql.FieldNotNull(FieldTraceID))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.State {
	return predicate.State(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.State {
	return predicate.State(sql.FieldContainsFold(FieldTraceID, v))
}

// HasInstrument applies the HasEdge predicate on the "instrument" edge.
func HasInstrument() predicate.State {
	return predicate.State(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstrumentTable, InstrumentColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.State
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstrumentWith applies the HasEdge predicate on the "instrument" edge with a given conditions (other predicates).
func HasInstrumentWith(preds ...predicate.Instrument) predicate.State {
	return predicate.State(func(s *sql.Selector) {
		step := newInstrumentStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Instrument
		step.Edge.Schema = schemaConfig.State
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.State) predicate.State {
	return predicate.State(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.State) predicate.State {
	return predicate.State(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.State) predicate.State {
	return predicate.State(sql.NotPredicates(p))
}
