// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Instrument is the predicate function for instrument builders.
type Instrument func(*sql.Selector)

// State is the predicate function for state builders.
type State func(*sql.Selector)

// SyncTask is the predicate function for synctask builders.
type SyncTask func(*sql.Selector)

// Timeframe is the predicate function for timeframe builders.
type Timeframe func(*sql.Selector)
